///////////////////////////////////////////////////////////
//  Map.cs
//  Implementation of the Class Map
//  Generated by Enterprise Architect
//  Created on:      20-may-2008 13:39:12
//  Original author: Lucía
///////////////////////////////////////////////////////////

using Invasiones.Dibujo;
using Invasiones.Debug;
using System.Xml;
using System;
using System.Collections.Generic;
using System.IO;
using Invasiones.Recursos;
using System.Drawing;
using Invasiones.Eventos;
using Invasiones.Map.PathFinding;
using System.Collections;
using Tao.Sdl;

namespace Invasiones.Map
{
	/// <summary>
	///Carga un m_mapa con formato de la aplicacion Tiled
	/// </summary>
	public class Mapa
	{

		/// <summary>
		/// La cantidad máxima de capas que puede tener un m_mapa
		/// </summary>
		private const int NRO_MAXIMO_DE_CAPAS = 8;

		/// <summary>
		/// La capa donde esta el terreno.
		/// </summary>
		public int CAPA_TERRENO;

		/// <summary>
		/// La capa donde esta el terreno.
		/// </summary>
		private int CAPA_OBSTACULOS;

		/// <summary>
		/// La capa donde esta el terreno.
		/// </summary>
		private int CAPA_UNIDADES_JUGADOR;

		/// <summary>
		/// Las posiciones invalidadas en el mapa.
		/// </summary>
		private int CAPA_POSICIONES_INVALIDADAS;

		/// <summary>
		/// Indica si el tile es visible en pantalla o no.
		/// </summary>
		public const int TILE_VISIBLE = 1;


		///// <summary>
		///// La cantidad máxima de tilesets que puede tener un m_mapa.
		///// </summary>
		//private const int NRO_MAXIMO_DE_TILESETS = 10;

		/// <summary>
		/// La capa donde esta la información de debug y otras.
		/// </summary>
		private const int CAPA_INFO = 8;

		/// <summary>
		/// El tileset que es utilizado para mostrar informacion de debug
		/// </summary>
		private static Tileset m_tilesetDebug;


		/// <summary>
		/// La camara, conteniendo la posición X, Y
		/// </summary>
		private Camara m_camara;

		/// <summary>
		/// La altura del m_mapa, en tiles. 0 < j < m_altoEnTiles
		/// </summary>
		private int m_altoEnTiles;

		/// <summary>
		/// El alto del mapa físico, en tiles.
		/// </summary>
		private int m_altoEnTilesMapaFisico;


		/// <summary>
		/// El ancho del m_mapa, en tiles. 0 < i < m_anchoEnTiles
		/// </summary>
		private int m_anchoEnTiles;

		/// <summary>
		/// El ancho del mapa físico, en tiles.
		/// </summary>
		private int m_anchoEnTilesMapaFisico;

		/// <summary>
		/// Los tilesets del m_mapa.
		/// </summary>
		private Tileset[] m_tilesets;

		/// <summary>
		/// La cantidad máxima de tilesets.
		/// </summary>
		private int m_tilesetMaximo;

		/// <summary>
		/// El m_mapa. Contiene los índices en el array m_image.
		/// </summary>
		private short[][,] m_mapa;

		/// <summary>
		/// Los nombres de las capas cargadas.
		/// </summary>
		private Hashtable m_nombresCapas;

		/// <summary>
		/// Dice si el m_mapa ha sido cargado o no.
		/// </summary>
		private bool m_mapaCargado;

		/// <summary>
		/// El número total de layers.
		/// </summary>
		private int m_numeroMaximoDeCapas;

		/// <summary>
		/// El ancho del tile a dibujar, en píxeles.
		/// </summary>
		private short m_tileAncho;

		/// <summary>
		/// La altura del tile a dibujar, en píxeles.
		/// </summary>
		private short m_tileAlto;

		/// <summary>
		/// El ancho del tile fisico, en píxeles.
		/// </summary>
		private int m_tileFisicoAncho;

		/// <summary>
		/// La altura del tile fisico, en píxeles.
		/// </summary>
		private int m_tileFisicoAlto;

		/// <summary>
		/// La posición del tile en i en el que esta apoyado el mouse.
		/// </summary>
		private Point m_tileMouse;

		/// <summary>
		/// La posición del tile en i en el que esta apoyado el mouse.
		/// </summary>
		private Point m_tileChicoMouse;

		/// <summary>
		/// El mapa con los tiles fisicos.
		/// </summary>
		private short[,] m_mapaTilesFisicos;

		/// <summary>
		/// El mapa con los tiles Visibles.
		/// </summary>
		private short[,] m_mapaTilesVisibles;

		/// <summary>
		/// Constructor de la clase
		/// </summary>
		public Mapa(Camara cam)
		{
			if (m_tilesets == null)
			{
				m_tilesets = new Tileset[Res.TLS_COUNT];
			}

			m_camara = cam;
		}

		/// <summary>
		/// Destructor de la clase
		/// </summary>
		~Mapa()
		{
			this.Dispose();
		}

		/// <summary>
		/// Elimina todos los tileset.
		/// </summary>
		public virtual void Dispose()
		{
			for (int i = 0; i < m_tilesets.Length; i++)
			{
				m_tilesets[i] = null;
			}
		}

#if DEBUG

		/// <summary>
		/// Muestra la informacion de debug del m_mapa
		/// </summary>
		/// <param name="g">el Video a donde pintar</param>
		/// <returns></returns>
		public void DibujarCapaInfo(Video g)
		{
#if MOSTRAR_INFO_MAPA
			g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[(int) Definiciones.FNT.SANS12], Definiciones.COLOR_BLANCO);
			g.SetearColor(Definiciones.COLOR_BLANCO);

			g.SetearColor(Definiciones.COLOR_NEGRO);
			g.LlenarRectangulo(460, 9, 120, 70);

			g.SetearColor(Definiciones.COLOR_BLANCO);
			g.Escribir("Tile: (" + m_tileMouse.X + ", " + m_tileMouse.Y + ") ", 10, 10, Superficie.H_CENTRO);
			g.Escribir("TileChico: (" + m_tileChicoMouse.X + ", " + m_tileChicoMouse.Y + ") ", 10, 20, Superficie.H_CENTRO);
			g.Escribir("Mouse: (" + Mouse.Instancia.X + ", " + Mouse.Instancia.Y + ") ", 10, 30, Superficie.H_CENTRO);
			g.Escribir("CamnraPos: (" + m_camara.X + ", " + m_camara.Y + ") ", 10, 40, Superficie.H_CENTRO);


			DibujarTile(g, m_tileMouse.X, m_tileMouse.Y);
			DibujarTileChico(g, m_tileChicoMouse.X, m_tileChicoMouse.Y, false);

			DibujarUltimoPathChico(g, PathFinder.Solucion);
#endif
		}

#endif
		Superficie m_imagenTileGris;

		/// <summary>
		/// Debuja el tile chico.
		/// </summary>
		/// <param name="g">EL video</param>
		/// <param name="i"></param>
		/// <param name="j"></param>
		public void DibujarTileChico(Video g, int i, int j, bool semiTrasparente)
		{
			if (i < 0 || j < 0 || i >= m_anchoEnTilesMapaFisico || j >= m_altoEnTilesMapaFisico)
			{
				return;
			}

			int posicionInicioX = m_camara.InicioX + (((i - j) * m_tileAncho / 2) >> 1) + m_camara.X + m_tileAncho / 4;
			int posicionInicioY = m_camara.InicioY + (((i + j) * m_tileAlto / 2) >> 1) + m_camara.Y;

			if (semiTrasparente)
			{
				if (m_imagenTileGris == null)
				{
					m_imagenTileGris = AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_TILE_GRIS);
					m_imagenTileGris.SetearAlpha(125);
				}
				g.Dibujar(m_imagenTileGris, 0, 0, 32, 16, (short)(posicionInicioX), (short)(posicionInicioY));

			}
			else
			{
				Rectangle rect = m_tilesetDebug.ObtenerRectanguloDelTile(Res.TILE_DEBUG_ID_TILE_CHICO);
				g.Dibujar(m_tilesetDebug.Imagen, (short)rect.X, (short)rect.Y, (short)rect.Width, (short)rect.Height, (short)(posicionInicioX), (short)(posicionInicioY));
			}
		}


		/// <summary>
		/// Dibuja el último path calculado en el Pathfinder.
		/// </summary>
		/// <param name="g"></param>
		/// <param name="stack"></param>
		private void DibujarUltimoPathChico(Video g, Stack<Point> stack)
		{
			if (stack == null)
			{
				return;
			}

			foreach (Point p in stack)
			{
				DibujarTileChico(g, p.X, p.Y, false);
			}
		}



		/// <summary>
		/// Dibuja el layer dado.
		/// </summary>
		/// <param name="g"> El graphics donde la capa va a ser escrita</param>
		/// <param name="layer">El número de layer a dibujar. 0 es el background</param>
		public bool DibujarCapa(Video g, int layer)
		{
			if (layer > m_numeroMaximoDeCapas || layer < 0)
			{
				Log.Instancia.Error("No se peude pintar el layer dado porque no existe.");
				return false;
			}

			if (!m_mapaCargado)
			{
				Log.Instancia.Error("El mapa no esta cargado aún");
				return false;
			}

			Rectangle oldClip = g.ObtenerClip();

			g.SetearClip(m_camara.InicioX, m_camara.InicioY, m_camara.Ancho, m_camara.Alto);


			bool cambio = true;

			Tileset tileSet;


			Point p = CalcularPrimerTileAPintar(m_camara.X, m_camara.Y);

			int XX = p.X;
			int YY = p.Y;


			int posicionInicioX = m_camara.InicioX + (((XX - YY) * m_tileAncho) >> 1) + m_camara.X;
			int posicionInicioY = m_camara.InicioY + (((XX + YY) * m_tileAlto) >> 1) + m_camara.Y;

			cambio = true;
			int tileX = 0;

			while (posicionInicioY <= (m_camara.Alto + m_camara.InicioY))
			{

				for (int i = XX, j = YY; (tileX * (m_tileAncho) + posicionInicioX) <= (m_camara.InicioX + m_camara.Ancho) && j >= 0; i++, j--)
				{
					if (i < m_altoEnTiles && i >= 0 && j < m_anchoEnTiles && j >= 0)
					{
						int tileId = m_mapa[layer][i, j];

						// Si el tile no esta vacío
						if (tileId != 0)
						{
							tileSet = ObtenerTileset(tileId);
							tileId = tileId - tileSet.PrimerGid;
							Rectangle finalRet = tileSet.ObtenerRectanguloDelTile(tileId);

							g.Dibujar(tileSet.Imagen, finalRet.X, finalRet.Y, finalRet.Width, finalRet.Height, (tileX * (m_tileAncho) + posicionInicioX), posicionInicioY);

#if DEBUG && MOSTRAR_INFO_MAPA

							g.Escribir("" + i + ", " + j, (short)((tileX * (m_tileAncho) + posicionInicioX) + 20), (short)(posicionInicioY), 0);
#endif

						}
					}
					tileX++;

				}

				tileX = 0;
				posicionInicioY += m_tileAlto >> 1;

				if (cambio == true)
				{
					XX++;
					cambio = false;
					posicionInicioX += m_tileAncho >> 1;
				}
				else
				{
					cambio = true;
					posicionInicioX -= m_tileAncho >> 1;
					YY++;
				}

			}
			g.SetearClip(oldClip.X, oldClip.Y, oldClip.Width, oldClip.Height);
			return true;

		}


		/// <summary>
		/// Se fija en donde empieza la pantalla. En que tile hay que empezar a pintar.
		/// </summary>
		/// <returns>El punto i, j del primer tile a pintar en el mapa.</returns>
		private Point CalcularPrimerTileAPintar(int x, int y)
		{
			Point p = new Point();

			int a = -y / m_tileAlto;
			int b = x / m_tileAncho;

			if (x > 0)
			{
				b++;
			}
			p.X = a - b;
			p.Y = a + b;

			p.X -= 1;
			p.X--;
			p.Y--;
			return p;
		}

		/// <summary>
		/// Actaliza el m_mapa. Se fija si scrollearon, por ejemplo.
		/// </summary>
		public void Actualizar()
		{
			//int timeAn = Sdl.SDL_GetTicks();

			if (!m_mapaCargado)
			{
				Log.Instancia.Error("El mapa no esta cargado aun");
				return;
			}
			Point p;
			if (Mouse.Instancia.X < m_camara.Borde)
			{
				if (m_camara.X + m_camara.Velocidad <= (m_anchoEnTiles * m_tileAncho) / 2)
				{
					p = CalcularPrimerTileAPintar(m_camara.X, m_camara.Y);

					if (p.X < -13)
					{
						m_camara.Y -= m_camara.Velocidad / 2;
					}
					else
					{
						p = CalcularPrimerTileAPintar(m_camara.X, m_camara.Y - m_camara.Alto);

						if (p.Y > m_altoEnTiles + 13)
						{
							m_camara.Y += m_camara.Velocidad / 2;
						}
					}
					m_camara.X += m_camara.Velocidad;

				}
			}

			if (Mouse.Instancia.Y > m_camara.Alto - m_camara.Borde)
			{
				if ((m_camara.Y - m_camara.Velocidad)
					>= (m_camara.Alto - m_altoEnTiles * m_tileAlto) &&
					m_camara.Y - m_camara.Velocidad <= 0)
				{
					p = CalcularPrimerTileAPintar(m_camara.X, m_camara.Y - m_camara.Alto);

					if (p.Y > m_altoEnTiles + 13)
					{
						m_camara.Y -= m_camara.Velocidad / 2;
						m_camara.X -= m_camara.Velocidad;
					}
					else
					{
						p = CalcularPrimerTileAPintar(m_camara.X - m_camara.Ancho, m_camara.Y - m_camara.Alto);
						if (p.X > m_anchoEnTiles + 13)
						{
							m_camara.Y -= m_camara.Velocidad / 2;
							m_camara.X += m_camara.Velocidad;
						}
						else
						{
							m_camara.Y -= m_camara.Velocidad;
						}
					}
				}
			}

			if (Mouse.Instancia.Y < m_camara.Borde)
			{
				if (m_camara.Y + m_camara.Velocidad <= 0)
				{
					p = CalcularPrimerTileAPintar(m_camara.X, m_camara.Y);

					if (p.X < -13)
					{
						m_camara.X -= m_camara.Velocidad;
						m_camara.Y += m_camara.Velocidad / 2;
					}
					else
					{
						p = CalcularPrimerTileAPintar(m_camara.X - m_camara.Ancho, m_camara.Y);

						if (p.Y < -13)
						{
							m_camara.X += m_camara.Velocidad;
							m_camara.Y += m_camara.Velocidad / 2;
						}
						else
						{
							m_camara.Y += m_camara.Velocidad;
						}
					}
				}
			}

			if (Mouse.Instancia.X > m_camara.Ancho - m_camara.Borde)
			{
				p = CalcularPrimerTileAPintar(m_camara.X - m_camara.Ancho, m_camara.Y);

				if ((m_camara.X - m_camara.Ancho - m_camara.Velocidad + m_tileAncho)
					>= -(m_anchoEnTiles * m_tileAncho) / 2 ||
					(m_camara.X - m_camara.Velocidad) > 0)
				{
					if (p.Y < -13)
					{
						m_camara.Y -= m_camara.Velocidad / 2;
					}
					else
					{
						p = CalcularPrimerTileAPintar(m_camara.X - m_camara.Ancho, m_camara.Y - m_camara.Alto);
						if (p.X > m_altoEnTiles + 13)
						{
							m_camara.Y += m_camara.Velocidad / 2;
						}
					}
					m_camara.X -= m_camara.Velocidad;
				}
			}

			ActualizarCoordenadasDelMouse();
			//int timeDesp = Sdl.SDL_GetTicks();

			//Log.Instancia.Debug("Tiempo actualizarMapa = " + (timeDesp - timeAn));
		}

		/// <summary>
		/// Se fija en qué tile esta apoyado el puntero del mouse.
		/// </summary>
		private void ActualizarCoordenadasDelMouse()
		{
			if (!m_mapaCargado)
			{
				Log.Instancia.Error("El mapa no esta cargado aun");
				return;
			}

			Point p = CalcularPosicionDelTileEnXY(Mouse.Instancia.X, Mouse.Instancia.Y);
			m_tileMouse.X = p.X;
			m_tileMouse.Y = p.Y;
		}

		/// <summary>
		/// Se fija a que tile del mapa pertenece la posición (x, y).
		/// </summary>
		/// <param name="x">El punto x a fijarse a donde pertenece.</param>
		/// <param name="y">El punto y a fijarse a donde pertenece.</param>
		/// <returns>El punto en i, j del tile al que pertenece el punto.</returns>
		private Point CalcularPosicionDelTileEnXY(int x, int y)
		{
			int a = 0;
			int b = 0;
			int restoX = 0;
			int restoY = 0;

			Point punto = new Point();


			a = ((y - m_camara.Y - m_camara.InicioY) / m_tileAlto);
			restoY = ((y - m_camara.Y - m_camara.InicioY) % m_tileAlto);

			if (x - m_camara.X > 0)
			{
				b = (x - m_camara.X - m_camara.InicioX) / m_tileAncho;
				restoX = (x - m_camara.X - m_camara.InicioX) % m_tileAncho;
			}
			else
			{
				b = (x - m_camara.X - m_camara.InicioX - m_tileAncho) / m_tileAncho;
				restoX = (x - m_camara.X - m_camara.InicioX - m_tileAncho) % m_tileAncho;
				restoX = -restoX;
			}

			punto.X = a + b;
			punto.Y = a - b;

			Rectangle rect = m_tilesetDebug.ObtenerRectanguloDelTile(Res.TILE_DEBUG_ID_TILES_VECINOS);
			restoY += m_tilesetDebug.AltoDelTile - m_tileAlto;

			int color = m_tilesetDebug.Imagen.ColorPixel(restoX, restoY);

			if (x - m_camara.X < 0)
			{
				if (color == Video.ConvertirColor(Definiciones.COLOR_ROJO))
				{
					punto.Y--;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_VERDE))
				{
					punto.X--;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_AZUL))
				{
					punto.X++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_CELESTE))
				{
					punto.Y++;
				}
			}
			else
			{
				if (color == Video.ConvertirColor(Definiciones.COLOR_ROJO))
				{
					punto.X--;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_VERDE))
				{
					punto.Y--;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_AZUL))
				{
					punto.Y++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_CELESTE))
				{
					punto.X++;
				}
			}

			m_tileChicoMouse.X = punto.X * 2;
			m_tileChicoMouse.Y = punto.Y * 2;

			rect = m_tilesetDebug.ObtenerRectanguloDelTile(Res.TILE_DEBUG_ID_TILE_CHICO_VECINOS);
			restoX += m_tileAncho * Res.TILE_DEBUG_ID_TILE_CHICO_VECINOS;

			color = m_tilesetDebug.Imagen.ColorPixel(restoX, restoY);

			if (x - m_camara.X < 0)
			{

				if (color == Video.ConvertirColor(Definiciones.COLOR_VERDE))
				{
					m_tileChicoMouse.Y++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_AZUL))
				{
					m_tileChicoMouse.X++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_CELESTE))
				{
					m_tileChicoMouse.X++;
					m_tileChicoMouse.Y++;
				}
			}
			else
			{
				if (color == Video.ConvertirColor(Definiciones.COLOR_VERDE))
				{
					m_tileChicoMouse.X++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_AZUL))
				{
					m_tileChicoMouse.Y++;
				}
				if (color == Video.ConvertirColor(Definiciones.COLOR_CELESTE))
				{
					m_tileChicoMouse.X++;
					m_tileChicoMouse.Y++;
				}

			}

			return punto; ;
		}

#if DEBUG
		/// <summary>
		/// Dibuja el tile (i, j) pasado por parámetro
		/// </summary>
		/// <param name="g">El Video a donde pintar.</param>
		/// <param name="i">La posición i del mapa.</param>
		/// <param name="j">La posición j del mapa-</param>
		public void DibujarTile(Video g, int i, int j)
		{
			if (i < 0 || j < 0 || i >= m_anchoEnTiles || j >= m_altoEnTiles)
			{
				return;
			}

			int posicionInicioX = m_camara.InicioX + (((i - j) * m_tileAncho) >> 1) + m_camara.X;
			int posicionInicioY = m_camara.InicioY + (((i + j) * m_tileAlto) >> 1) + m_camara.Y;

			Rectangle rect = m_tilesetDebug.ObtenerRectanguloDelTile(Res.TILE_DEBUG_ID_CAMINO_A_SEGUIR);
			g.Dibujar(m_tilesetDebug.Imagen, (short)rect.X, (short)rect.Y, (short)rect.Width, (short)rect.Height, (short)(posicionInicioX), (short)(posicionInicioY));
		}
#endif

		/// <summary>
		/// Se fija a qué tileset pertenece el tileId.
		/// </summary>
		/// <param name="tileId">El id del tile a pasar.</param>
		/// <returns>Devuelve aqui una referencia al tileset a la que pertenece el tile dado.</returns>
		public Tileset ObtenerTileset(int tileId)
		{
			int i = 0;
			Tileset tileset = null;
			while (i < m_tilesetMaximo)
			{
				if (tileId >= m_tilesets[i].PrimerGid)
				{
					tileset = m_tilesets[i];
				}
				i++;
			}
			return tileset;
		}

		/// <summary>
		/// Carga el m_mapa.
		/// </summary>
		/// <param name="mapId">El Id del m_mapa a cargar.</param>
		public bool Cargar(int mapId)
		{

			if (m_mapaCargado)
			{
				m_mapa = null;
			}

			m_tilesetMaximo = 0;
			m_numeroMaximoDeCapas = 0;

			if (AdministradorDeRecursos.Instancia.PathsEscenarios == null)
			{
				Log.Instancia.Error("No se puede cargar el mapa porque hubo algun error durante la carga de los paths");
				return false;
			}

			if (mapId < Res.TLS_COUNT || mapId >= (Res.TLS_COUNT + Res.MAP_COUNT))
			{
				Log.Instancia.Error("Map ID " + mapId + " inválido ");
				return false;
			}


			if (!LeerInfoMapa(mapId))
			{
				return false;
			}

			if (!LeerTilesets(mapId))
			{
				return false;
			}

			if (!LeerCapas(mapId))
			{
				return false;
			}

			//Empiezo a leer el m_mapa.

			CargarCapaInfo();

			m_mapaCargado = true;
			return true;
		}


		/// <summary>
		/// Lee las capas de mapa mapId
		/// </summary>
		/// <param name="mapId">El id del mapa a cargar</param>
		/// <returns>true si pudo leer las capas correctamente.</returns>
		private bool LeerCapas(int mapId)
		{
			XmlTextReader lector = new XmlTextReader(AdministradorDeRecursos.Instancia.PathsEscenarios[mapId]);
			string encoding;
			m_nombresCapas = new Hashtable();

			try
			{
				while (lector.Read())
				{
					if (lector.NodeType == XmlNodeType.Element && lector.Name == "layer")
					{
						lector.MoveToAttribute("name");

						if (lector.Name == "name")
						{
							m_nombresCapas.Add(lector.Value, m_numeroMaximoDeCapas);
							switch (lector.Value.Trim().ToLower())
							{
								case "obstaculos":
									{
										CAPA_OBSTACULOS = m_numeroMaximoDeCapas;
									}
									break;

								case "terreno":
									{
										CAPA_TERRENO = m_numeroMaximoDeCapas;
									}
									break;

								case "unidades":
									{
										CAPA_UNIDADES_JUGADOR = m_numeroMaximoDeCapas;
									}
									break;

								case "posicion invalidada":
									{
										CAPA_POSICIONES_INVALIDADAS = m_numeroMaximoDeCapas;
									}
									break;
							}
						}

						encoding = "";

						// termino de leer el resto de la capa.
						while (lector.Read() && !(lector.NodeType == XmlNodeType.EndElement && lector.Name == "layer"))
						{
							if (lector.NodeType == XmlNodeType.Element)
							{
								if (lector.Name == "data")
								{
									lector.MoveToAttribute("encoding");
									if (lector.Name == "encoding")
									{
										encoding = lector.Value;
									}

									//Convierto la data en el mapa.
									string data = lector.ReadString();

									if (encoding == "base64")
									{
										if (m_mapa == null)
										{
											//Creo el m_mapa con la cantidad máxima de capas + 1 
											//para la capa de informacion j debug.
											m_mapa = new short[NRO_MAXIMO_DE_CAPAS + 1][,];
										}

										data = data.Trim();
										byte[] decbuff = Convert.FromBase64String(data);

										if (m_numeroMaximoDeCapas == NRO_MAXIMO_DE_CAPAS)
										{
											lector.Close();
											return false;
										}
										int index = 0;
										m_mapa[m_numeroMaximoDeCapas] = new short[m_altoEnTiles, m_anchoEnTiles];
										for (int i = 0; i < m_altoEnTiles; i++)
										{
											for (int j = 0; j < m_anchoEnTiles; j++)
											{
												m_mapa[m_numeroMaximoDeCapas][j, i] = decbuff[index];
												index += 4;
											}
										}
										m_numeroMaximoDeCapas++;
									}
								}
							}
						} //termino de leer el layer
					}
				}

				lector.Close();
				lector = null;
			}
			catch (Exception e)
			{
				Log.Instancia.Error("Error al leer el archivo xml " + AdministradorDeRecursos.Instancia.PathsEscenarios[mapId] + ". " + e.Message);
				lector.Close();
				lector = null;
				return false;
			}
			return true;
		}

		/// <summary>
		/// Lee los tilesets que estan dentro del mapa apId.
		/// </summary>
		/// <param name="mapId">el id del mapa a leer</param>
		/// <returns>true si pudo leer los tilesets correctamente.</returns>
		private bool LeerTilesets(int mapId)
		{
			XmlTextReader lector = new XmlTextReader(AdministradorDeRecursos.Instancia.PathsEscenarios[mapId]);

			try
			{

				while (lector.Read())
				{
					if (lector.NodeType == XmlNodeType.Element && lector.Name == "tileset")
					{

						Tileset tileSet = new Tileset();

						while (lector.MoveToNextAttribute())
						{

							if (lector.Name == "firstgid")
							{
								tileSet.PrimerGid = Convert.ToInt16(lector.Value);
							}

							if (lector.Name == "source")
							{
								string path = Utilidades.ObtenerPath(Path.Combine(Programa.PATH_ESCENARIOS, lector.Value));
								if (path == null)
								{
									return false;
								}

								tileSet.Cargar(path);
							}
						}
						m_tilesets[m_tilesetMaximo++] = tileSet;
					}
				}
			}
			catch (Exception e)
			{
				Log.Instancia.Error("No se pudieron cargar los tilesets." + e);
				lector.Close();
				lector = null;
				return false;
			}

			lector.Close();
			lector = null;
			return true;

		}

		/// <summary>
		/// Lee la información del mapa: las dimensiones del mapa.
		/// </summary>
		/// <param name="mapId">El id del mapa a leer.</param>
		/// <returns>true si pudo cargar bien el mapa.</returns>
		private bool LeerInfoMapa(int mapId)
		{

			int tileCamaraI = 0;
			int tileCamaraJ = 0;

			XmlTextReader lector = new XmlTextReader(AdministradorDeRecursos.Instancia.PathsEscenarios[mapId]);
			try
			{

				while (lector.Read())
				{
					if (lector.NodeType == XmlNodeType.Element && lector.Name == "map")
					{
						lector.MoveToAttribute("orientation");

						if (lector.Name == "orientation")
						{
							if (lector.Value != "isometric")
							{
								return false;
							}
						}

						//Leo el ancho del mapa.
						lector.MoveToAttribute("width");
						if (lector.Name == "width")
						{
							m_anchoEnTiles = Convert.ToInt16(lector.Value);
							m_anchoEnTilesMapaFisico = m_anchoEnTiles * 2;

						}
						else
						{
							Log.Instancia.Error("No se puede leer el ancho del mapa.");
							return false;
						}

						//Leo el alto del mapa
						lector.MoveToAttribute("height");
						if (lector.Name == "height")
						{
							m_altoEnTiles = Convert.ToInt16(lector.Value);
							m_altoEnTilesMapaFisico = m_altoEnTiles * 2;
						}
						else
						{
							Log.Instancia.Error("No se puede leer el alto del mapa.");
							return false;
						}

						//Leo el ancho del tile
						lector.MoveToAttribute("tilewidth");
						if (lector.Name == "tilewidth")
						{
							m_tileAncho = Convert.ToInt16(lector.Value);
							m_tileFisicoAncho = m_tileAncho / 2;
						}
						else
						{
							Log.Instancia.Error("No se puede leer el ancho del tile.");
							return false;
						}

						//Leo el alto del tile.
						lector.MoveToAttribute("tileheight");
						if (lector.Name == "tileheight")
						{
							m_tileAlto = Convert.ToInt16(lector.Value);
							m_tileFisicoAlto = m_tileAlto / 2;
						}
						else
						{
							Log.Instancia.Error("No se puede leer el alto del tile.");
							return false;
						}

					}

					//leo el elemento properties, es una lista con propiedades especificas del mapa:
					if (lector.NodeType == XmlNodeType.Element && lector.Name == "properties")
					{

						while (lector.Read() && !(lector.NodeType == XmlNodeType.EndElement && lector.Name == "properties"))
						{
							if (lector.NodeType == XmlNodeType.Element)
							{
								if (lector.Name == "property")
								{
									lector.MoveToAttribute("name");
									if (lector.Name == "name")
									{
										switch (lector.Value)
										{
											case "CamaraTileInicialJ":
												lector.MoveToAttribute("value");
												if (lector.Name == "value")
												{
													tileCamaraJ = Convert.ToInt16(lector.Value);
												}
												break;
											case "CamaraTileInicialI":
												lector.MoveToAttribute("value");

												if (lector.Name == "value")
												{
													tileCamaraI = Convert.ToInt16(lector.Value);
												}
												break;
										}
									}
								}
							}
						}
					}
				}
				m_camara.X = ((tileCamaraJ - tileCamaraI) * m_tileAncho) >> 1;
				m_camara.Y = -((tileCamaraJ + tileCamaraI) * m_tileAlto) >> 1;

			}
			catch (Exception e)
			{
				Log.Instancia.Error("No se puede leer el mapa. " + e);
				lector.Close();
				return false;
			}

			lector.Close();
			lector = null;
			return true;
		}

		/// <summary>
		/// Carga la capa que contine la información sobre que tiles puede ser 
		/// caminables y cuales no.
		/// Utilizada por la clase PathFinding
		/// </summary>
		private void CargarCapaInfo()
		{
			if (m_tilesetDebug == null)
			{
				m_tilesetDebug = new Tileset();
			}

			m_tilesetDebug.Cargar(AdministradorDeRecursos.Instancia.PathsEscenarios[Res.TLS_DEBUG]);
			m_mapa[CAPA_INFO] = new short[m_altoEnTiles, m_anchoEnTiles];

			Tileset tileset;

			m_mapaTilesFisicos = new short[m_altoEnTiles * 2, m_anchoEnTiles * 2];

			for (int capa = 0; capa < m_numeroMaximoDeCapas; capa++)
			{
				for (int i = 0; i < m_anchoEnTiles; i++)
				{
					for (int j = 0; j < m_altoEnTiles; j++)
					{
						//Cargo la informacion de los tiles en cada mapa
						//BUG FIX: Se invalidan los tiles de los edificios igualmente porque sino se puede llegar a borrar
						//el edificio.
						tileset = ObtenerTileset(m_mapa[capa][i, j]);
						if (tileset != null && tileset.Id != Res.TLS_UNIDADES /*&& tileset.Id != Res.TLS_EDIFICIOS && tileset.Id != Res.TLS_ENFERMERIA*/)
						{
							m_mapa[CAPA_INFO][i, j] = tileset.Id;
							m_mapaTilesFisicos[i * 2, j * 2] = tileset.Id;
							m_mapaTilesFisicos[i * 2, j * 2 + 1] = tileset.Id;
							m_mapaTilesFisicos[i * 2 + 1, j * 2] = tileset.Id;
							m_mapaTilesFisicos[i * 2 + 1, j * 2 + 1] = tileset.Id;

						}
					}
				}
			}
			PathFinder.Instancia.CargarMapa(this);
		}


		/// <summary>
		/// Get del alto del mapa.
		/// </summary>
		public int Alto
		{
			get
			{
				return m_altoEnTiles;
			}
		}

		/// <summary>
		/// Get del ancho del mapa.
		/// </summary>
		public int AltoMapaFisico
		{
			get
			{
				return m_altoEnTilesMapaFisico;
			}
		}

		/// <summary>
		/// Get del ancho del mapa.
		/// </summary>
		public int Ancho
		{
			get
			{
				return m_anchoEnTiles;
			}
		}

		/// <summary>
		/// Get del ancho del mapa.
		/// </summary>
		public int AnchoMapaFisico
		{
			get
			{
				return m_anchoEnTilesMapaFisico;
			}
		}

		/// <summary>
		/// Devuelve el alto del tile.
		/// </summary>
		public int TileAlto
		{
			get
			{
				return m_tileAlto;
			}
		}

		/// <summary>
		/// Devuelve el alto del tile.
		/// </summary>
		public int TileFisicoAlto
		{
			get { return m_tileFisicoAlto; }
		}

		/// <summary>
		/// Devuelve el ancho del tile fisico.
		/// </summary>
		public int TileAncho
		{
			get { return m_tileAncho; }
		}

		/// <summary>
		/// Devuelve el ancho del tile fisico.
		/// </summary>
		public int TileFisicoAncho
		{
			get
			{
				return m_tileFisicoAncho;
			}
		}

		/// <summary>
		/// Devuelve el tile en el que esta el cursor.
		/// </summary>
		public Point TileBajoMouse
		{
			get
			{
				return m_tileMouse;
			}
		}

		/// <summary>
		/// Devuelve el tile chico en el que esta el cursor.
		/// </summary>
		public Point TileChicoMouse
		{
			get
			{
				return m_tileChicoMouse;
			}
		}

		/// <summary>
		/// Devuelve la capa de unidades.
		/// </summary>
		public short[,] CapaUnidades
		{
			get
			{
				return m_mapa[CAPA_UNIDADES_JUGADOR];
			}
		}

		/// <summary>
		/// Devuelve los tiles fisicos (transformados en tiles mas chicos)
		/// </summary>
		public short[,] CapaTilesFisicos
		{
			get
			{
				return m_mapaTilesFisicos;
			}
		}

		/// <summary>
		/// Devuelve los tiles fisicos (transformados en tiles mas chicos)
		/// </summary>
		public short[,] CapaTilesVisibles
		{
			get
			{
				return m_mapaTilesVisibles;
			}

			set
			{
				m_mapaTilesVisibles = value;
			}
		}


		/// <summary>
		/// Devuelve la capa de unidades.
		/// </summary>
		public short[,] CapaObstaculos
		{
			get
			{
				return m_mapa[CAPA_OBSTACULOS];
			}
		}

		/// <summary>
		/// Devuelve la capa de unidades.
		/// </summary>
		public short[,] CapaEdificios
		{
			get
			{
				return m_mapa[CAPA_POSICIONES_INVALIDADAS];
			}
		}

		/// <summary>
		/// Devuelve la capa de unidades.
		/// </summary>
		public short[,] CapaTerreno
		{
			get
			{
				return m_mapa[CAPA_TERRENO];
			}
		}


		/// <summary>
		/// Devuelve los tilesets
		/// </summary>
		public Tileset[] Tilesets
		{
			get
			{
				return m_tilesets;
			}
		}

		/// <summary>
		/// Se fija si la posicion x, y es caminable.
		/// </summary>
		public bool EsPosicionCaminable(int x, int y)
		{
			if (x < 0 || y < 0 || x >= (m_anchoEnTiles << 1) || y >= (m_altoEnTiles << 1))
			{
				return false;
			}

			return m_mapaTilesFisicos[x, y] == Res.TLS_PASTO || m_mapaTilesFisicos[x, y] == Res.TLS_TIERRA;
		}


        /// <summary>
        /// Se fija si la posicion x, y es caminable.
        /// </summary>
        public void InvalidarTile(int x, int y)
        {
            if (x < 0 || y < 0 || x + 1>= (m_anchoEnTiles << 1) || y + 1 >= (m_altoEnTiles << 1))
            {
                return ;
            }

            m_mapaTilesFisicos[x, y] = Res.TLS_ARBOLES;


            m_mapaTilesFisicos[x+1, y] = Res.TLS_ARBOLES;
            m_mapaTilesFisicos[x+1, y+1] = Res.TLS_ARBOLES;
            m_mapaTilesFisicos[x, y+1] = Res.TLS_ARBOLES;
        }




		public Point ObtenerPosicionEnLineaDeVision(int x1, int x2, int y1, int y2)
		{
			float columna = x1;
			float fila = y1;

			float decliveFila = ObtenerDecliveFila(x1, x2, y1, y2);
			float decliveColumna = ObtenerDecliveColumna(x1, x2, y1, y2);
			Log.Instancia.Debug("pos2: {" + x2 + ", " + y2 + "}, pos1: {" + x1 + ", " + y1 + "}");

			// Voy desde (x1, y1) a (x2, y2)
			if (Math.Abs(decliveFila) == 1)
			{
				while ((int)(Math.Floor(fila)) != y2)
				{
					if (EsPosicionCaminable((int)(Math.Floor(columna)), (int)(Math.Floor(fila))))
					{
						return new Point((int)(Math.Floor(columna)), (int)(Math.Floor(fila)));
					}
					// Incremento la fila y la columna
					fila += decliveFila;
					columna += decliveColumna;
					Log.Instancia.Debug("c: f:" + columna + ", " + fila);
				}
			}
			else
			{
				while ((int)(Math.Floor(columna)) != x2)
				{
					if (EsPosicionCaminable((int)(Math.Floor(columna)), (int)(Math.Floor(fila))))
					{
						return new Point((int)(Math.Floor(columna)), (int)(Math.Floor(fila)));
					}

					// Incremento la fila y la columna
					fila += decliveFila;
					columna += decliveColumna;
					Log.Instancia.Debug("c: f:" + columna + ", " + fila);
				}
			}
			return new Point(-1, -1);
		}

		private float ObtenerDecliveFila(int x1, int x2, int y1, int y2)
		{
			if (Math.Abs(y2 - y1) > Math.Abs(x2 - x1))
			{
				return y2 > y1 ? 1 : -1;
			}
			else
			{
				float declive = (float)(Math.Abs(y2 - y1)) / (float)(Math.Abs(x2 - x1));
				declive *= y2 > y1 ? 1 : -1;
				return declive;
			}
		}

		private float ObtenerDecliveColumna(int x1, int x2, int y1, int y2)
		{
			if (Math.Abs((float)x2 - x1) > ((float)y2 - y1))
				return (x2 > x1 ? 1 : -1);
			else
			{
				float declive = Math.Abs((float)(x2 - x1) / (float)(y2 - y1));
				declive *= (x2 > x1 ? 1 : -1);
				return declive;
			}

		}
	}//end Map

}//end namespace Game