///////////////////////////////////////////////////////////
//  Tile.cs
//  Implementation of the Class Tile
//  Generated by Enterprise Architect
//  Created on:      01-ago-2008 20:19:16
//  Original author: Administrador
///////////////////////////////////////////////////////////

namespace Invasiones.Map
{
    /// <summary>
    /// Representa a un tile
    /// </summary>
    public class Tile
    {
        #region Declaraciones

		/// <summary>
		/// El id del tile.
		/// </summary>
        private short m_id;

		/// <summary>
		/// Utilizado para saber cual es la cantidad de las unidades a poner en el tile.
		/// </summary>
		private int m_cantidad;

        /// <summary>
        /// El costo de moverse en el tile . 99999 si no se puede moverse sobre ese tile.
        /// </summary>
        private short m_costo;
        #endregion

        #region Properties
        public short Id
        {
            get
            {
                return m_id;
            }
            set
            {
                m_id = value;
            }
        }

		public int Cantidad
		{
			get
			{
				return m_cantidad;
			}
			set
			{
				m_cantidad = value;
			}
		}

        public short Costo
        {
            get
            {
                return m_costo;
            }
            set
            {
                m_costo = value;
            }
        }
        #endregion

        #region Constructores
        /// <summary>
        /// Cnstructor de la clase.
        /// </summary>
        public Tile()
        {

        }
        #endregion

        #region Destructor - libera recursos
        /// <summary>
        /// Destructor
        /// </summary>
        ~Tile()
        {
            this.Dispose();
        }

        /// <summary>
        /// Libera los recursos stomados.
        /// </summary>
        public virtual void Dispose()
        {

        }
        #endregion
    }//end Tile
}//end namespace Map