///////////////////////////////////////////////////////////
//  Grupo.cs
//  Implementation of the Class grupo
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 3:33:53
//  Original author: Lucía
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using Invasiones.Dibujo;
using Invasiones.Debug;
using System.Drawing;
using System;
using Invasiones.Map;

namespace Invasiones.Nivel.Unidades
{
	/// <summary>
	/// Es una coleccion de unidades que ha sido agrupada por el usuario por
	/// conveniencia. Es un grupo complejo. Tiene una orientacion (frente, fondo,
	/// flanco derecho, flanco izquierdo). Cada unidad en la grupo trata de
	/// mantener su posicion unica relativa a la posicion dentro de la grupo.
	/// </summary>
	public class Grupo
	{
		#region Enumeraciones

        private static Random s_random;

        private const int MAX_ID_GRUPO = 99999;

        /// <summary>
        /// El id del grupo al que pertenezco;
        /// </summary>
        private int m_idGrupo;
		
        /// <summary>
		/// La separacion entre las unidades, medido en tiles chicos.
		/// </summary>
		public const int SEPARACION_ENTRE_UNIDADES = 2;

		/// <summary>
		/// Maxima distancia que puede haber entre unidades.
		/// Utilizado para sacar el mínimo.
		/// </summary>
		public const int MAXIMA_DISTANCIA = 99999;

		/// <summary>
		/// Estado en el que puede estar la unidad
		/// </summary>
		public enum ESTADO
		{
			ESPERANDO_ORDEN,
			AGRUPANDO,
			MOVIENDO,
			SANANDO,
			ATANCANDO,
            ELIMINADO,
            PERSIGUIENDO_ENEMIGO
		}

		#endregion

		#region Atributos

		/// <summary>
		/// La inteligencia que posee la unidad.
		/// </summary>
		public IA m_inteligencia;

		/// <summary>
		/// El proximo estado en el que va a estar el grupo.
		/// </summary>
		private Grupo.ESTADO m_proximoEstado;

		/// <summary>
		/// La orden que tiene que cumplir el grupo.
		/// </summary>
		private Orden m_ordenObjetivo;

		/// <summary>
		/// El mapa terreno.
		/// </summary>
		private static Mapa s_mapa;

		/// <summary>
		/// El tile objetivo a seguir cuando se le da la orden de moverse a las unidades.
		/// </summary>
		private Point m_tileObjetivo;

		/// <summary>
		/// Me dice que es lo que tiene que hacer la grupo.
		/// </summary>
		private Orden m_ordenRecibida;

		/// <summary>
		/// Me dice que es lo que tiene que hacer la grupo.
		/// </summary>
		private bool m_cumplioOrden;

		/// <summary>
		/// el estado actual en el que se encuentra el grupo.
		/// </summary>
		private Grupo.ESTADO m_estado;

		///// <summary>
		///// Utilizada por varios motivos..
		///// </summary>
		//private int m_cuenta;

		/// <summary>
		/// Es una lista que contiene todas las unidades en la formación.
		/// </summary>
		private List<Unidad> m_unidades;

		/// <summary>
		/// La velocidad máxima a la que se puede mover el grupo. Es la velocidad de la
		/// unidad que tiene menor velocidad dentro de grupo.
		/// </summary>
		private int m_velocidad;

		/// <summary>
		/// Dice si la grupo esta siendo seleccionada o no.
		/// </summary>
		private bool m_esSeleccionada;

		/// <summary>
		/// Es el comandante de la grupo.
		/// </summary>
		private Unidad m_comandante;

		/// <summary>
		/// Los puntos de resistencia en promedio.
		/// </summary>
		private int m_promedioSalud;

		/// <summary>
		/// Los puntos de resistencia en promedio.
		/// </summary>
		private int m_promedioPuntosDeResistencia;

		#endregion

		#region propiedades
		/// <summary>
		/// Devuelve el promedio total de los puntos de resistencia de la grupo
		/// </summary>
		public int Salud
		{
			get
			{
				return m_promedioSalud;
			}
		}

		/// <summary>
		/// Devuelve el promedio total de los puntos de resistencia de la grupo
		/// </summary>
		public int PuntosDeResistencia
		{
			get
			{
				return m_promedioPuntosDeResistencia;
			}
		}
		#endregion

		/// <summary>
		/// Libera las referencias a las unidades.
		/// </summary>
		public virtual void Dispose()
		{
			m_unidades = null;
		}

        static Grupo()
        {
            s_random = new Random();
        }


		/// <summary>
		/// Constructor de la clase
		/// </summary>
		/// <param name="unidades">Una lista que contiene las unidades seleccionadas</param>
		public Grupo(List<Unidad> unidades)
		{

            m_idGrupo = s_random.Next(0, MAX_ID_GRUPO);

			if (unidades == null)
			{
				return;
			}

			m_unidades = unidades;
			m_velocidad = 100;

			m_promedioPuntosDeResistencia = 0;

			foreach (Unidad unidad in unidades)
			{
                unidad.AdherirmeAGrupo(this);

				if (unidad.Velocidad.X < m_velocidad)
				{
					m_velocidad = unidad.Velocidad.X;
				}
				m_promedioPuntosDeResistencia += unidad.PuntosDeResistencia;
			}

            //m_estado = ESTADO.ESPERANDO_ORDEN;
			m_promedioPuntosDeResistencia = m_promedioPuntosDeResistencia / m_unidades.Count;
		}

		/// <summary>
		/// Mueve las unidades a la posicion deseada, formando un cuadrado.
		/// </summary>
		private void MoverUnidadesAPosicionesDeseadas()
		{
			const int IZQ = 0;
			const int ARR = 1;
			const int DER = 2;
			const int ABJ = 3;

			const int INCREMENTO_ESPIRAL = 2;
			const int INCREMENTO_UNIDADES = 2;

			int x = m_comandante.PosicionEnTileFisico.X;
			int y = m_comandante.PosicionEnTileFisico.Y;

			int i = 0;
			int j = 0;
			int inc = INCREMENTO_ESPIRAL;

			int cant = m_unidades.Count;


			//m_comandante.OffsetEnFormacion = new Point(0 ,0);
			m_comandante.OffsetEnFormacion = new Point(i, j);


			int dir = ARR;

			int puestos = 1;
			int indice = 0;

			//Recorro el mapa en forma de espiral apra encontrar una posicion cercana...
			while (puestos != cant)
			{
				if (s_mapa.EsPosicionCaminable(x + i, y + j) && m_unidades[indice] != m_comandante)
				{
					//Le determino el offset
					m_unidades[indice].OffsetEnFormacion = new Point(i, j);

					//Lo muevo a donde tiene que ir..
					m_unidades[indice].Mover(x + i, y + j);
					m_unidades[indice].SetearOrdenDeObjetivo(m_ordenObjetivo);
					puestos++;
					indice++;
				}
				else if (m_unidades[indice] == m_comandante)
				{
					m_comandante.Parar();
					indice++;
				}
				

				if (dir == ARR)
				{
					i += INCREMENTO_UNIDADES;
					if (i == inc)
					{
						dir = DER;
						continue;
					}
				}

				if (dir == DER)
				{
					j += INCREMENTO_UNIDADES;

					if (j == inc)
					{
						dir = ABJ;

						continue;
					}
				}

				if (dir == IZQ)
				{
					j -= INCREMENTO_UNIDADES;
					if (j == -inc)
					{
						dir = ARR;
						inc += INCREMENTO_ESPIRAL;
						continue;
					}
				}

				if (dir == ABJ)
				{
					i -= INCREMENTO_UNIDADES;
					if (i == -inc)
					{
						dir = IZQ;
						continue;
					}
				}
			}
		}

		/// <summary>
		/// Actualiza toda la grupo.
		/// </summary>
		public void Actualizar()
		{

            Log.Instancia.Debug("Estado: " + m_estado);

			switch (m_estado)
			{
				case ESTADO.ESPERANDO_ORDEN:
					ActualizarEstadoEsperandoOrden();
					break;

				case ESTADO.MOVIENDO:
					ActualizarEstadoMoviendo();
					break;

				case ESTADO.AGRUPANDO:
					ActualizarEstadoAgrupando();
                    break;

                case ESTADO.PERSIGUIENDO_ENEMIGO:
                    ActualizarEstadoPersiguiendoEnemgigo();
                    break;

				case ESTADO.ATANCANDO:
					ActualizarEstadoAtacando();
					break;

				case ESTADO.SANANDO:
					ActualizarEstadoSanando() ;
					break;

                case ESTADO.ELIMINADO:
                    return;
			}


			ChequearSaludCumplioOrden();
			EliminarUnidadesMuertas();

            if (m_unidades.Count <= 1)
            {
                SetearEstado(ESTADO.ELIMINADO);
            }

                

            if (m_comandante != null && m_comandante.EstaMuerto())
            {
                Log.Instancia.Debug("El comandante esta muerto, seteo uno nuevo.");
                SetearComandanteAuxiliar();
            }

			return;
		}

        /// <summary>
        /// 
        /// </summary>
        private void ActualizarEstadoPersiguiendoEnemgigo()
        {
           
        }

		/// <summary>
		/// Actualiza las unidades sanandose.
		/// </summary>
		private void ActualizarEstadoSanando()
		{
			bool cumplio = true;
			foreach (Unidad unidad in m_unidades)
			{
				if (unidad.Salud != unidad.PuntosDeResistencia)
				{
					cumplio = false;
				}
			}

			if (cumplio)
			{
				Log.Instancia.Debug("Todos estan sanos...");
				SetearEstado(ESTADO.ESPERANDO_ORDEN);
			}
		}

		/// <summary>
		/// Chequea si el grupo cumplio la orden recibida.
		/// </summary>
		private void ChequearSaludCumplioOrden()
		{
			if (m_ordenRecibida == null)
			{
				Log.Instancia.Debug("El grupo no tiene ninguna orden seteada.");
				return;
			}

			m_promedioSalud = 0;
			foreach (Unidad unit in m_unidades)
			{
				m_promedioSalud += unit.Salud;

				switch (m_ordenRecibida.Id)
				{
					case Orden.TIPO.MOVER:
						if (unit.CumplioOrdenObjetivoMover())
						{
							Log.Instancia.Debug("El grupo cumplio la orden.");
							m_cumplioOrden = true;
						
						}
						break;
				}
			}

            if (m_unidades.Count > 0)
            {
                m_promedioSalud = m_promedioSalud / m_unidades.Count;
                if (m_cumplioOrden)
                {
                    SetearEstado((int)ESTADO.ESPERANDO_ORDEN);
                }
            }
            else
            {
                m_promedioSalud = 0;
            }
		}

		/// <summary>
		/// Elimino las unidades que se murieron del
		/// </summary>
		private void EliminarUnidadesMuertas()
		{
			List<Unidad> muertos = new List<Unidad>();
			m_promedioSalud = 0;

			foreach (Unidad unidad in m_unidades)
			{
				if (unidad.EstaMuerto())
				{
					muertos.Add(unidad);
				}
				else
				{
					m_promedioSalud += unidad.Salud;
				}
			}

			if (muertos.Count > 0)
			{
				foreach (Unidad unimuerto in muertos)
				{
                    //if (unimuerto == m_comandante)
                    //{
                    //    SetearComandanteAuxiliar();
                    //}
					m_unidades.Remove(unimuerto);
				}

				m_promedioPuntosDeResistencia = 0;

				if (m_unidades.Count != 0)
				{
					foreach (Unidad unidades in m_unidades)
					{
						m_promedioPuntosDeResistencia += unidades.PuntosDeResistencia;
					}

					m_promedioPuntosDeResistencia = m_promedioPuntosDeResistencia / m_unidades.Count;
				}
			}

            if (m_unidades.Count != 0)
            {
                m_promedioSalud = m_promedioSalud / m_unidades.Count;
            }
            else
            {
                m_promedioSalud = 0;
            }
		}

		/// <summary>
		/// Chequea si el grupo no recibio una nueva orden.
		/// </summary>
		private void ActualizarEstadoEsperandoOrden()
		{
			//me fijo si el grupo tiene inteligencia.
			if (m_inteligencia != null)
			{
				if (m_ordenRecibida == null)
				{
					m_ordenRecibida = m_inteligencia.ProximaOrden();
				}

				if (m_ordenRecibida != null && m_ordenRecibida.Id == Orden.TIPO.MOVER)
				{
					SetearOrdenObjetivo(Orden.TIPO.MOVER, m_ordenRecibida.Punto.X, m_ordenRecibida.Punto.Y);
					Mover(m_ordenRecibida.Punto.X, m_ordenRecibida.Punto.Y);
				}
			}
		}

		/// <summary>
		/// Setea la orden que tiene que cumplir el grupo, para determinar si se cumplio la orden recibida o no.
		/// </summary>
		/// <param name="idOrden">EL tipo de orden.</param>
		/// <param name="x">La posicion x en donde tiene que cumplir la orden.</param>
		/// <param name="y">La posicion y en donde tiene que cumplir la orden.</param>
		private void SetearOrdenObjetivo(Orden.TIPO idOrden, int x, int y)
		{
			m_ordenObjetivo = new Orden(idOrden, x, y);
		}

		/// <summary>
		/// Setea un comandante mas porque el anterior se murio.
		/// </summary>
		private void SetearComandanteAuxiliar()
		{
            if (m_unidades.Count >= 2)
            {
                m_comandante = m_unidades[0];
                m_comandante.MarcarComoComandante();
            }
		}

		/// <summary>
		/// Actualiza el estado formando. Estado en el que se encuentra el grupo 
		/// cuando esta tratando de formar el cuadrado
		/// </summary>
		private void ActualizarEstadoAgrupando()
		{
			//Chequea que las unidades esten en las posiciones deseadas. 
			//Si todas las unidades estan en ocio, entonces
			foreach (Unidad unidad in m_unidades)
			{
				if (unidad.EstadoActual != (int)Unidad.ESTADO.OCIO)
				{
                    Log.Instancia.Debug("Estado actual unidad: " + unidad.EstadoActual);

					return;
				}
			}

			//Si la orden recibida es la orden mover
            if (m_ordenRecibida != null && (m_ordenRecibida.Id == Orden.TIPO.MOVER || m_ordenRecibida.Id == Orden.TIPO.SANAR))
			{
				m_comandante.Mover(m_tileObjetivo.X, m_tileObjetivo.Y);
				if (m_comandante.CaminoASeguir == null)
				{
					//BUG FIX.
					SetearEstado(ESTADO.ESPERANDO_ORDEN);
					return;
				}

				SetearEstado(ESTADO.MOVIENDO);

				foreach (Unidad unidad in m_unidades)
				{
					unidad.CalcularCaminoADistancia(m_comandante.CaminoASeguir, unidad.OffsetEnFormacion.X, unidad.OffsetEnFormacion.Y);
				}
			}
		}

		/// <summary>
		///Actualiza el estado atacando de la unidad.
		/// </summary>
		private void ActualizarEstadoAtacando()
		{
			throw new System.NotImplementedException();
		}

		/// <summary>
		/// Actualiza el estado moviendo de la formación.
		/// </summary>
		private void ActualizarEstadoMoviendo()
		{
			bool todosEnOcio = true;

			foreach (Unidad unidad in m_unidades)
			{

                //Me fijo si todas las unidades estan en ocio.
				if (unidad.EstadoActual != Unidad.ESTADO.OCIO)
				{
                    if (m_ordenRecibida.Id == Orden.TIPO.SANAR)
                    {
                        if (unidad.EstadoActual != Unidad.ESTADO.SANANDO)
                        {
                            todosEnOcio = false;
                        }
                    }
                    else
                    {
						todosEnOcio = false;
                    }
				}
				else 
				{
                    if (m_ordenRecibida.Id == Orden.TIPO.SANAR)
                    {
                        if (unidad.Salud != unidad.PuntosDeResistencia)
                        {
                            Log.Instancia.Debug("Me dicen ue me sane..");
                            unidad.RecuperarSalud();
                        }
                    }
				}
			}

			if (todosEnOcio)
			{
				Log.Instancia.Debug("Todos en ocio!!!!");
				SetearEstado(m_proximoEstado);
			}
		}

		/// <summary>
		/// Dibuja todas las unidades padre la pantalla.
		/// </summary>
		/// <param name="g">La pantalla adonde se van a pintar las unidades</param>
		public bool Dibujar(Video gfx)
		{
			return false;
		}


		/// <summary>
		/// Setea el comandante de la formación.
		/// </summary>
		private void SetearComandante()
		{
			m_comandante = m_unidades[0];
            m_comandante.MarcarComoComandante();

			//TODO: ver porque no anda cuando seteo el comandante mas cercano al punto a ir.

			//double distanciaMinima = MAXIMA_DISTANCIA;
			//double dist;

			//foreach (Unidad unidad in m_unidades)
			//{
			//    dist = unidad.CalcularDistancia(m_tileObjetivo.X, m_tileObjetivo.Y);

			//    if (dist < distanciaMinima)
			//    {
			//        distanciaMinima = dist;
			//        m_comandante = unidad;
			//    }
			//}
		}

		/// <summary>
		/// Da la orden de atacar a todas las unidades
		/// </summary>
		/// <param name="enemigo">La unidad a la que tiene que atacar la formación</param>
		public void Atacar(Unidad enemigo)
		{

            foreach (Unidad unidad in m_unidades)
            {
                unidad.Atacar(enemigo);
            }
            //Log.Instancia.Debug("Atacando al enemigo: ");

            //m_enemigoAAtacar = enemigo;
            //m_blanco = new Point(-1, -1);

            //SetearEstado(ESTADO.PERSIGUIENDO_ENEMIGO);

            //return false;
		}

        ///// <summary>
        ///// Setea el estado atacando de la unidad.
        ///// </summary>
        //private void SetearAtacando()
        //{

        //    MoverUnidadesAPosicionesDeseadas();

        //    SetearEstado(ESTADO.PERSIGUIENDO_ENEMIGO);

        //}

		/// <summary>
		/// Mueve toda la formación
		/// </summary>
		/// <param name="x">El punto x a donde se tiene que mover la grupo.</param>
		/// <param name="y">El punto y a donde se tiene que mover la grupo</param>
		public void Mover(int x, int y)
		{
			m_ordenRecibida = new Orden(Orden.TIPO.MOVER, x, y);
			SetearEstado(ESTADO.AGRUPANDO);
			m_tileObjetivo = new Point(x, y);

			//Seteo el comandante, si no tiene seteado uno.
			if (m_comandante == null)
			{
				SetearComandante();
			}
			m_proximoEstado = ESTADO.ESPERANDO_ORDEN;

			MoverUnidadesAPosicionesDeseadas();
		}

		/// <summary>
		/// Setea el estado de la formación.
		/// </summary>
		/// <param name="estado">El estado en el que se encuentra la formación.</param>
		private void SetearEstado(Grupo.ESTADO estado)
		{
			m_estado = estado;
			if (estado == ESTADO.ESPERANDO_ORDEN)
			{
				m_cumplioOrden = false;
				m_ordenRecibida = null;
			}
		}

		#region Propiedades


		/// <summary>
		/// El mapa con las unidades. 
		/// </summary>
		public static Mapa Mapa
		{
			get
			{
				return s_mapa;
			}
			set
			{
				s_mapa = value;
			}
		}


		/// <summary>
		/// Propiedad si es seleccionada la unidad.
		/// </summary>
		public bool EsSeleccionado
		{
			get
			{
				return m_esSeleccionada;
			}
			set
			{
				if (m_unidades == null)
				{
					return;
				}

				foreach (Unidad unidad in m_unidades)
				{
					unidad.EsSeleccionada = value;
				}

				m_esSeleccionada = value;
			}
		}

		/// <summary>
		/// Devuelve el estado en el que se encuentra la grupo
		/// </summary>
		public Grupo.ESTADO EstadoActual
		{
			get
			{
				return m_estado;
			}
		}

		/// <summary>
		/// Devuelve la lista de unidades
		/// </summary>
		public List<Unidad> Unidades
		{
			get
			{
				return m_unidades;
			}
			set
			{
				m_unidades = value;
			}
		}

        /// <summary>
        /// La cantidad de soldados de la unidad.
        /// </summary>
        public int CantidadDeSoldados
        {
            get
            {
                return m_unidades.Count;
            }

        }

		/// <summary>
		/// devuelve la maxima velocidad a la que peude desplazarse la grupo.
		/// </summary>
		public int MaximaVelocidad
		{
			get
			{
				return m_velocidad;
			}
			set
			{
				m_velocidad = value;
			}
		}
		#endregion

		/// <summary>
		/// Setea la inteligencia de la unidad
		/// </summary>
		/// <param name="intel"></param>
		public void SetearInteligencia(IA intel)
		{
			m_inteligencia = intel;
			SetearEstado((int)ESTADO.ESPERANDO_ORDEN);
		}

		/// <summary>
		/// Se le da a la formacion la orden de sanarse.
		/// </summary>
		public void Sanar(int x, int y)
		{
			m_ordenRecibida = new Orden(Orden.TIPO.SANAR, x, y);

            if (m_comandante == null)
            {
                SetearComandanteAuxiliar();
            }

            Point p = s_mapa.ObtenerPosicionEnLineaDeVision(x, m_comandante.PosicionEnTileFisico.X, y, m_comandante.PosicionEnTileFisico.Y);

            if (p.X == -1 || p.Y == -1)
            {
                Log.Instancia.Debug("No se puede mandar a sanar al grupo.");
                return;
            }

            SetearSanar(p.X, p.Y);
        }

        public int Id
        {
            get
            {
                return m_idGrupo;
            }

        }

        /// <summary>
		/// Setea el estado sanar;
		/// </summary>
		/// <param name="x">La posicion x en donde sanar.</param>
		/// <param name="y">La posicion y en donde sanar.</param>
		private void SetearSanar(int x, int y)
		{
			Mover(x, y);
            m_ordenRecibida = new Orden(Orden.TIPO.SANAR, x, y);
			m_proximoEstado = ESTADO.SANANDO;
		}

        public Unidad ObtenerUltimaUnidad()
        {
            if (m_unidades.Count == 1)
            {
                return m_unidades[0];
            }
            return null;
        }

        public void EliminarGrupo()
        {
            foreach (Unidad unidad in m_unidades)
            {
                unidad.SalirDelGrupo();
            }
        }

        public void EliminarUnidad(Unidad unidad)
        {
            m_unidades.Remove(unidad);

            if (unidad == m_comandante)
            {
                m_comandante = null;
                unidad.DesmarcarComandante();

                SetearComandanteAuxiliar();
            }

            if (m_unidades.Count <= 1)
            {
                SetearEstado(ESTADO.ELIMINADO);
            }
        }
    }//end grupo

}//end namespace Nivel