///////////////////////////////////////////////////////////
//  Enemigo.cs
//  Implementation of the Class Enemigo
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 3:53:18
//  Original author: Lucía
///////////////////////////////////////////////////////////

using Invasiones.Dibujo;
using System;
using Invasiones.Map;
using Invasiones.GUI;
using Invasiones.Nivel.Unidades;
using System.Collections.Generic;
using System.Drawing;
using Invasiones.Eventos;
using Invasiones.Debug;

namespace Invasiones.Nivel.Jugadores
{
	/// <summary>
	/// Es la clase que contiene la inteligencia artificial del enemigo.
	/// </summary>
	public class BandoEnemigo : Jugador
	{
		#region Constructores
		/// <summary>
		/// Constructor del enemigo
		/// </summary>
		public BandoEnemigo(Mapa map, Camara cam, ref Objeto[,] objAPintar, Hud hud)
			: base(map, cam, objAPintar, hud)
		{
			m_bando = (int)Episodio.BANDO.ENEMIGO;
		}
		#endregion


		#region Metodos Override
		/// <summary>
		/// Actuliza todas las unidades controladas. Itera por cada unidad y llama al
		/// método actualizar de la unidad.
		/// </summary>
		public override void Actualizar()
		{
			switch (m_estado)
			{
				case ESTADO.INICIO:
					m_estado = ESTADO.CARGANDO;
					break;

				case ESTADO.CARGANDO:
					// TODO: aca deberian cargarse la lista de unidades del bando ingles y la organizacion
					// de las mismas, grupos, integrantes por grupo, etc.

					m_estado = ESTADO.JUEGO;
					break;

				case ESTADO.JUEGO:
					ActualizarEstadoJuego();
					break;
			}
		}

		/// <summary>
		/// Carga las unidades del enemigo.
		/// </summary>
		/// <returns>true si las pudo cargar correctamente</returns>
		public override bool CargarUnidades(int nroNivel)
		{
			Tileset tileSet = null;

			for (int i = 0; i < m_mapa.Tilesets.Length; i++)
			{
				if (m_mapa.Tilesets[i].Id == Res.TLS_UNIDADES)
				{
					tileSet = m_mapa.Tilesets[i];
					break;
				}
			}

			m_unidades = new List<Unidad>();

			//Paso a convertir el mapa leido en unidades.
			for (int i = 0; i < m_mapa.Ancho; i++)
			{
				for (int j = 0; j < m_mapa.Alto; j++)
				{
					if (m_mapa.CapaUnidades[i, j] != 0)
					{
						if (tileSet.Tiles[m_mapa.CapaUnidades[i, j] - tileSet.PrimerGid].Id
							== Res.UNIDAD_INGLES)
						{

							List<Unidad> lista = PosicionarUnidades(Res.UNIDAD_INGLES, tileSet.Tiles[m_mapa.CapaUnidades[i, j] - tileSet.PrimerGid].Cantidad, i << 1, j << 1);

							if (lista.Count > 1)
							{
								if (m_grupos == null)
								{
									m_grupos = new List<Grupo>();
								}

								Grupo nuevoGrupo = new Grupo(lista);

								IA inteli = new IA();
								inteli.Cargar(i, j, nroNivel);
								nuevoGrupo.SetearInteligencia(inteli);

								m_grupos.Add(nuevoGrupo);
							}
							else
							{
								foreach (Unidad uni in lista)
								{
									uni.Patrullar();
								}
							}
						}
					}
				}
			}
			return true;
		}
		#endregion

		#region Metodos
		/// <summary>
		/// Actualiza el estado juego en la unidad.
		/// </summary>
		private void ActualizarEstadoJuego()
		{
			//Borro las unidades seleccionadas de antes.
			m_unidadesSeleccionadas = new List<Unidad>();

			ActualizarUnidades();

			EliminarUnidadesMuertas();

			ActualizarOrdenes();

			ActualizarGrupos();
		}

		/// <summary>
		/// Actualiza los grupos
		/// </summary>
		private void ActualizarGrupos()
		{
			if (m_grupos == null || m_grupos.Count == 0)
			{
				return;
			}

			//Actualizp los grupos efectivamente..
			foreach(Grupo grupo in m_grupos)
			{
				grupo.Actualizar();
			}
		}

		/// <summary>
		/// Actualiza las ordenes puestas a las unidades.
		/// </summary>
		private void ActualizarOrdenes()
		{
			if (m_unidadesSeleccionadas == null || m_unidadesSeleccionadas.Count == 0)
			{
				return;
			}

			if (Mouse.Instancia.BotonesApretados.Contains(Mouse.BOTON_IZQ))
			{
				foreach (Unidad unidad in m_unidadesSeleccionadas)
				{
					unidad.EsSeleccionada = false;
				}

				BorrarUnidadesSeleccionadas();
			}
		}
		#endregion
	}//end Enemigo
}//end namespace Enemy