///////////////////////////////////////////////////////////
//  PathFinder.cs
//  Implementation of the Class Nodo
//  Generated by Enterprise Architect
//  Created on:      04-ago-2008 19:55:15
//  Original author: Lucía
///////////////////////////////////////////////////////////

using System.Drawing;
using System.Collections.Generic;
using Invasiones.Debug;
using System;

namespace Invasiones.Map.PathFinding
{

    /// <summary>
    /// Esta clase se encara de encontrar el camino mas corto, viable, dado dos puntos
    /// (uno de inicio j uno de fin)
    /// </summary>
	public class PathFinder
	{
		/// <summary>
		/// El maximo tiempo que determina si se puede ir o no a la posicion.
		/// En décima de segungos.
		/// </summary>
		private const int HARDC_MAXIMO_TIEMPO_DEC_PATHFINDING = 45;

		/// <summary>
		/// Representa un nodo en el m_mapa.
		/// </summary>
		private class Nodo
		{
			/// <summary>
			/// el padre del nodo actual.
			/// </summary>
			public Nodo Padre;

            /// <summary>
            /// EL costo g (del inglés m_objetivo). Es el costo de ir desde el nodo 
            /// de inicio hasta este nodo
            /// </summary>
            public int CostoG;

            /// <summary>
            /// El costo h (del inglés Heuristic) del nodo.Es el costo estimado de ir desde este 
            /// nodo al nodo objetivo.
            /// </summary>
            public int CostoH;

            /// <summary>
            /// El costo f (del inglés fitness) del nodo. Es a suma de los costos g j h. 
            /// F representa el costo, muy aproximado, de ir desde el nodo inicio hasta este 
            /// nodo. Mientras menor sea este costo, mejor será el camino.
            /// </summary>
            public int CostoF;

            /// <summary>
            /// El punto en el mapa donde se encuentra
            /// </summary>
            public int I;

            /// <summary>
            /// El punto en el mapa donde se encuentra
            /// </summary>
            public int J;

            /// <summary>
            /// Contructor 
            /// </summary>
            public Nodo()
            {
            }

            /// <summary>
            /// Construcor 2
            /// </summary>
            /// <param name="j">la posicion j edl nodo</param>
            /// <param name="i">la posicion  del nodo</param>
            public Nodo(int i, int j)
            {
                I = i;
                J = j;
            }

            /// <summary>
            /// Sobrecarga del método Equals
            /// </summary>
            /// <param name="obj">Objeto a ver sis on iguales</param>
            /// <returns>true si son iguales</returns>
            public override bool Equals(System.Object obj)
            {
                // Si el parametro es null devuelvo false
                if (obj == null)
                {
                    return false;
                }

                // Si el parametro no se puede castear a Nodo, devuelvo false
                Nodo p = obj as Nodo;
                if ((Object)p == null)
                {
                    return false;
                }

                // Devuelve true si los campos coinciden
                return I == p.I && J == p.J;
            }

            /// <summary>
            /// Sobrecarga del método Equals
            /// </summary>
            /// <param name="obj">Objeto a ver sis on iguales</param>
            /// <returns>true si son iguales</returns>
            public bool Equals(Nodo obj)
            {
                // Si el parametro no se puede castear a Nodo, devuelvo false
                Nodo p = obj as Nodo;
                if ((Object)p == null)
                {
                    return false;
                }

                // Devuelve true si los campos coinciden
                return I == p.I && J == p.J;
            }

            /// <summary>
            /// Sobrecarga del operador ==
            /// </summary>
            /// <param name="a">Nodo 1 a comparar</param>
            /// <param name="b">Nodo 2 a comparar</param>
            /// <returns>true si estan en la misma ubicación.</returns>
            public static bool operator ==(Nodo a, Nodo b)
            {
                //si ambos son null o ambos tienen la misma instancia, devuelvo true
                if (Object.ReferenceEquals(a, b))
                {
                    return true;
                }


                // Si uno es null, pero no ambos, devuelvo false.
                if (((object)a == null) || ((object)b == null))
                {
                    return false;
                }

                // Devuelve true si los campos coinciden
                return a.I == b.I && a.J == b.J;
            }

            /// <summary>
            /// Sobrecarga del operador !=
            /// </summary>
            /// <param name="a">Nodo 1 a comparar</param>
            /// <param name="b">Nodo 2 a comparar</param>
            /// <returns>true si son distintos.</returns>
            public static bool operator !=(Nodo a, Nodo b)
            {
                return !(a == b);
            }

            /// <summary>
            /// No se cambia nada..
            /// </summary>
            public override int GetHashCode()
            {
                return base.GetHashCode();
            }

        }//end Nodo


        // Métodos de la clase PathFinder


        /// <summary>
        /// Costo de moverse de un tile a otro.
        /// </summary>
        private const int COSTO_DIAGONAL = 14;

        /// <summary>
        /// Costo de moverse de un tile a otro, pero en diagonal.
        /// </summary>
        private const int COSTO_DERECHO = 10;

        /// <summary>
        /// Costo de moverse a un tile que  es un obstaculo.
        /// </summary>
        private const int COSTO_IMPOSIBLE = 99999;

        /// <summary>
        /// El punto desde donde se comienza.
        /// </summary>
        private Nodo m_inicio;

        /// <summary>
        /// El punto a donde se tiene que llegar.
        /// </summary>
        private Nodo m_objetivo;

        /// <summary>
        /// Lista de nodos abiertos. Consiste  en la lista de todos los nodos
        /// que no han sido explorados aún. Un nodo es considerado explorad si 
        /// si el algoritmo a mirado a cada nodo conectado a este.
        /// </summary>
        private List<Nodo> m_nodosAbiertos;

        /// <summary>
        /// Lista de nodos cerrados. Consiste en la lista de todos los nodos
        /// que ya han sido explorados. Un nodo es considerado explorad si 
        /// si el algoritmo a mirado a cada nodo conectado a este.
        /// </summary>
        private List<Nodo> m_nodosCerrados;

        /// <summary>
        /// Contiene las posiciones del m_mapa, con los costos asociados al mismo
        /// </summary>
        private short[,] m_mapaTilesFisicos;

		/// <summary>
		/// La referencia al mapa. Utilizado para saber ciertos atributos del mapa, como el ancho
		/// el alto o cuales posiciones son caminables
		/// </summary>
		private Mapa m_mapa;

        /// <summary>
        /// Ls instancia de la clase
        /// </summary>
        private static PathFinder m_instancia;

#if DEBUG
        /// <summary>
        /// Contiene el último pathfinding calculado.
        /// </summary>
        public static Stack<Point> Solucion;
#endif

        /// <summary>
        /// Costructor de la clase
        /// </summary>
        private PathFinder()
        {
        }

        /// <summary>
        /// Destructor de la clase
        /// </summary>
        ~PathFinder()
        {
            this.Dispose();
        }

        /// <summary>
        /// Libera los nodos utilizados
        /// </summary>
        public virtual void Dispose()
        {
           
        }

        /// <summary>
        ///  Devuelve la instancia de la clase PathFinder
        /// </summary>
        public static PathFinder Instancia
        {
            get 
            {
                if (m_instancia == null)
                {
                    m_instancia = new PathFinder();
                }
                return m_instancia;
            }
        }

        /// <summary>
        /// Carga el mapa.
        /// </summary>
        /// <param name="objetosMapa">EL mapa conteniendo los ids de los obstaculos</param>
        /// <returns>true si pudo cargar bien</returns>
        public bool CargarMapa(Mapa mapa)
        {
            if (mapa == null || mapa.CapaTilesFisicos == null)
            {
                return false;
            }

            m_mapaTilesFisicos = mapa.CapaTilesFisicos;

			m_mapa = mapa;

            return true;
        }

        /// <summary>
        /// Devuelve el camino mas corto dado dos puntos, en una pila. Si no se encuentra
        /// un camino válido, devuelve null.
        /// </summary>
        /// <param name="inicioI">Posición i del inicio.</param>
        /// <param name="inicioJ">Posición j de inicio</param>
        /// <param name="objetivoI">Posición i de objetivo.</param>
        /// <param name="objetivoJ">Posición j de objetivo.</param>
        /// <returns>Devuelve una pila con el camino mas corto o null
        /// si el camino no es posible.</returns>
        public Stack<Point> EncontrarCaminoMasCorto(int inicioI, int inicioJ, int objetivoI, int objetivoJ)
        {
			/* Read the initial time. */
			DateTime startTime = DateTime.Now;


            if (m_mapaTilesFisicos == null)
            {
                Log.Instancia.Advertir("No se puede encontrar el camino mas corto porque no esta cargado el mapa aún. ");
                return null;
            }

            //Creo las listas de nodos abiertos j cerrados
            m_nodosAbiertos = new List<Nodo>();
            m_nodosCerrados = new List<Nodo>();

            //Creo un nodo con la posicion de inicio.
            //Los costos F, G, H son 0.
            m_inicio = new Nodo(inicioI, inicioJ);
            m_objetivo = new Nodo(objetivoI, objetivoJ);


			if (!m_mapa.EsPosicionCaminable(objetivoI, objetivoJ))
			{
				Log.Instancia.Debug("No se puede encontrar un camino a la posicion porque no es válida.");
				return null;
			}

            Nodo nuevoNodo = m_inicio;
            Nodo mejorNodo = new Nodo();

            // agrego el nodo inicio a la lista de abiertos
            m_nodosAbiertos.Add(nuevoNodo);
			DateTime ahora = DateTime.Now;
			TimeSpan res = new TimeSpan(HARDC_MAXIMO_TIEMPO_DEC_PATHFINDING * (1000000));

            //mientras la lista no este vacia
			while (m_nodosAbiertos.Count != 0)
			{
				ahora = DateTime.Now;
				TimeSpan resta = ahora - startTime;
				if (resta > res)
				{
					Log.Instancia.Debug("EL pathfinding esta tardando mucho, posiblemente es porque no hay un camino que llegue.: " + resta);
					return null;
				}

				mejorNodo = SeleccionarMejorNodoDeListaAbiertos();

				//lo saco de la lista de nodos abiertos.


				//Si el mejor nodo es el nodo objetivo -> entonces encontre el camino mas corto.
				if (mejorNodo == m_objetivo)
                {
                    m_nodosCerrados.Add(mejorNodo);
                    m_nodosAbiertos.Remove(mejorNodo);

#if DEBUG
                    Solucion = ObtenerSolucion();

					/* Read the end time. */
					DateTime stopTime = DateTime.Now;

					/* Compute the duration between the initial and the end time. */
					TimeSpan duration = stopTime - startTime;
					
                    return Solucion;
#else
                    return ObtenerSolucion();
#endif
                }

                //si la lista quedo vacia entonces no hay camino.
                if (m_nodosAbiertos.Count == 0)
                {
                    return null;
                }

                AgregarHijos(mejorNodo);

                m_nodosCerrados.Add(mejorNodo);
                m_nodosAbiertos.Remove(mejorNodo);
            }

            return null;
        }

        /// <summary>
        /// Agrega los nodos adyaacentes a la lista de abiertos
        /// </summary>
        /// <param name="padre">El padre cuyo nodos adyacentes van a ser explorados.</param>
        private void AgregarHijos(Nodo padre)
        {
            bool arr = AbrirNodo(ref padre, padre.I - 1, padre.J, COSTO_DERECHO);
            bool der = AbrirNodo(ref padre, padre.I, padre.J + 1, COSTO_DERECHO);
            bool abj = AbrirNodo(ref padre, padre.I + 1, padre.J, COSTO_DERECHO);
            bool izq = AbrirNodo(ref padre, padre.I, padre.J - 1, COSTO_DERECHO);

            if (arr && der)
            {
                AbrirNodo(ref padre, padre.I - 1, padre.J + 1, COSTO_DIAGONAL);
            }
            if (der && abj)
            {
                AbrirNodo(ref padre, padre.I + 1, padre.J + 1, COSTO_DIAGONAL);
            }
            if (abj && izq)
            {
                AbrirNodo(ref padre, padre.I + 1, padre.J - 1, COSTO_DIAGONAL);
            }
            if (izq && arr)
            {
                AbrirNodo(ref padre, padre.I - 1, padre.J - 1, COSTO_DIAGONAL);
            }
        }

        /// <summary>
        /// Se fija cual es el mejor nodo de la lista de abiertos.
        /// </summary>
        /// <returns>El nodo con el menor costo F de la lista de abiertos.</returns>
        private Nodo SeleccionarMejorNodoDeListaAbiertos()
        {
            Nodo mejor = new Nodo();
            mejor.CostoF = COSTO_IMPOSIBLE;

            foreach (Nodo n in m_nodosAbiertos)
            {
                if (n.CostoF < mejor.CostoF)
                {
                    mejor = n;
                }
            }

            if (mejor.CostoF == COSTO_IMPOSIBLE) //Esto no creo que pase nunca.
            {
                return null;
            }
            return mejor;
        }

        /// <summary>
        /// Busca cual es la solucion dentro de los nodos cerrados j los devuelve en una pila.
        /// </summary>
        /// <returns></returns>
        private Stack<Point> ObtenerSolucion()
        {
            Stack<Point> solucion = new Stack<Point>();

            Nodo nuevo = new Nodo();
			Nodo hijo = null;
            nuevo = m_nodosCerrados[m_nodosCerrados.IndexOf(m_objetivo)];
            solucion.Push(new Point(nuevo.I, nuevo.J));

            while (nuevo.Padre != null)
            {
				hijo = nuevo;
				nuevo = m_nodosCerrados[m_nodosCerrados.IndexOf(nuevo.Padre)];

				if (nuevo != null)
				{
					solucion.Push(new Point(nuevo.I, nuevo.J));
				}
            }

            return solucion;
        }

    
        /// <summary>
        /// Agrega j devuelve un nodo a la lista de NodosAbiertos
        /// </summary>
        /// <param name="padre">Nodo padre</param>
        /// <param name="i">la posición i en el m_mapa de nodos</param>
        /// <param name="j">la posición j en el m_mapa de nodos</param>
        /// <param name="costo">el costo de moverse desde el padre hasta el nodo [i,
        /// j]</param>
        /// <returns>Si la posicion es caminable o no.</returns>
        private bool AbrirNodo(ref Nodo padre, int i, int j, int costo)
        {
            if (!m_mapa.EsPosicionCaminable(i, j))
            {
                return false;
            }

            Nodo hijo = new Nodo(i, j);

            //si esta en la lista de nodos cerrados, lo ignoro.
            if (m_nodosCerrados.Contains(hijo))
            {
                return true;
            }

            //Seteo los costos del nodo
            hijo.CostoG = costo + padre.CostoG;
            hijo.CostoH = (Math.Abs(i - m_objetivo.I) + Math.Abs(j - m_objetivo.J)) * COSTO_DERECHO;
            hijo.CostoF = hijo.CostoG + hijo.CostoH;

            hijo.Padre = padre;

            //Si todavía no esta en la lista de nodos abiertor, entonces lo agrego.
            if (!m_nodosAbiertos.Contains(hijo))
            {
                m_nodosAbiertos.Add(hijo);
            }
            else
            { 
                //Si ya esta en la lisa de nodos abiertos, chequeo que el 
                //camino a este cuadrado  es mejor, utilizando el costo G para 
                //medirlo. Si es asi, cambio el padre del tile al tile actual y recalculo 
                //los costos G y F;
                Nodo h;
                h = m_nodosAbiertos[m_nodosAbiertos.IndexOf(hijo)];
                if (hijo.CostoF < h.CostoF)
                {
                    m_nodosAbiertos.Remove(h);
                    m_nodosAbiertos.Add(hijo);
                }
            }
            return true;
        }

	
		/// <summary>
		/// Adhiere el caminoAAdherir al caminoViejo
		/// </summary>
		/// <param name="caminoViejo"></param>
		/// <param name="caminoAAdherir"></param>
		public void AdherirCamino(Stack<Point> caminoViejo, Stack<Point> caminoAAdherir)
		{
			Stack<Point> pilaAuxiliar = new Stack<Point>();
			while (caminoAAdherir.Count != 0)
			{
				pilaAuxiliar.Push(caminoAAdherir.Pop());
			}

			while (pilaAuxiliar.Count != 0)
			{
				Point tile = pilaAuxiliar.Pop();
				caminoViejo.Push(tile);
			}
		}
	}//end PathFinder//end Nodo

}//end namespace PathFinding