///////////////////////////////////////////////////////////
//  Boton.cs
//  Implementation of the Class Boton
//  Generated by Enterprise Architect
//  Created on:      04-ago-2008 20:09:00
//  Original author: Administrador
///////////////////////////////////////////////////////////

using Invasiones.Dibujo;
using Invasiones.Recursos;
using System;
using Invasiones.Eventos;
using Invasiones.Debug;

namespace Invasiones.GUI
{
	/// <summary>
	/// Representa a un botón.
	/// </summary>
	public class Boton : CajaGUI
	{
		public const int OFFSET_LIMITE_PANTALLA = 15;
		public const int ALTO = 25;
		public const int ANCHO = 100;
		public const int ANCHO_MINIMO = 10;
		public const int ALTO_MINIMO = 10;

		#region Atributos
		/// <summary>
		/// La imagen de fondo del botón, cuando el puntero del mouse esta sobre la imagen.
		/// </summary>
		protected Superficie m_imagenSel;

		/// <summary>
		/// si el mouse se encuentra arriba del boton o no.
		/// </summary>
        protected bool m_debajoDelPuntero;

        public bool DebajoDelPuntero
        {
            get
            {
                return m_debajoDelPuntero;
            }
        }


		#endregion

		#region Propiedades


		#endregion

		#region Constructores
		/// <summary>
		/// Constructor de la clase.
		/// </summary>
		/// <param name="leyenda">El string a ser escrito sobre el botón.</param>
		/// <param name="imagen">La imagen a mostrar cuando el mouse no esta sobre el botón.</param>
		/// <param name="imagenSel">La imagen a mostrar cuando el mouse esta sobre el botón.</param>
		/// <param name="fuente">La fuente a utilizar para escibir la leyenda.</param>
		//public Boton(int leyenda, Superficie imagen, Superficie imagenSel, Fuente fuente)
		public Boton(int leyenda, Fuente fuente)
		{
			m_alto = Boton.ALTO;
			m_ancho = Boton.ANCHO;


			m_imagen = AdministradorDeRecursos.Instancia.ObtenerImagenAlpha(Res.IMG_BOTON);
			m_alto = m_imagen.Alto;
			m_ancho = m_imagen.Ancho;


			m_imagenSel = AdministradorDeRecursos.Instancia.ObtenerImagenAlpha(Res.IMG_BOTON_SELECCION);

			m_fuente = fuente;

			if (fuente == null)
			{
				m_fuente = AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FUENTE_BOTON];
			}

			m_leyenda = leyenda;
		}

		#endregion


		#region Metodos

		public override void SetearPosicion(int x, int y, int ancla)
		{
			m_x = x;
			m_y = y;

			if ((ancla & Superficie.V_CENTRO) != 0)
			{ 
				m_y += (Video.Alto>>1) - (m_alto>>1);
			}

			if ((ancla & Superficie.H_CENTRO) != 0)
			{
				m_x += (Video.Ancho >> 1) - (m_ancho >> 1);
			}
		}
		/// <summary>
		/// Actualiza el botón.
		/// </summary>
		/// <returns>true si el boton fue apretado. </returns>
		public override int Actualizar()
		{
			if (Mouse.Instancia.X > m_x && Mouse.Instancia.X < m_x + m_ancho && Mouse.Instancia.Y > m_y && Mouse.Instancia.Y < m_alto + m_y)
			{
				m_debajoDelPuntero = true;
			}
			else
			{
				m_debajoDelPuntero = false;
			}

			if (m_debajoDelPuntero && Mouse.Instancia.BotonesApretados.Contains(Mouse.BOTON_IZQ))
			{
				Mouse.Instancia.BotonesApretados.Remove(Mouse.BOTON_IZQ);
				return 1;
			}

			return 0;
		}

		/// <summary>
		/// Dibuja el botón en pantalla.
		/// </summary>
		/// <param name="gfx">El graphics donde se dibujará el botón.</param>
		/// <param name="g">La pantalla a donde pintar el botón.</param>
		/// <param name="x">La posición en x en donde pintar el botón.</param>
		/// <param name="y">La posición en y donde pintar el botón.</param>
		/// <param name="ancla">El ancla desde donde tomar el (x, y)</param>
		public override void Dibujar(Video g)
		{
			if (m_debajoDelPuntero)
			{
				if (m_imagenSel != null)
				{
					g.Dibujar(m_imagenSel, m_x, m_y, 0);
				}
				else
				{
					g.SetearColor(Definiciones.GUI_COLOR_SELECCION);
					g.LlenarRectangulo(m_x, m_y, m_ancho, m_alto, Definiciones.GUI_ALPHA, 0);
				}
			}
			else
			{
				if (m_imagen != null)
				{
					g.Dibujar(m_imagen, m_x, m_y, 0);
				}
				else
				{
					g.SetearColor(Definiciones.GUI_COLOR_MENUS);
					g.LlenarRectangulo(m_x, m_y, m_ancho, m_alto, Definiciones.GUI_ALPHA, 0);
				}
			}

			g.SetearFuente(m_fuente, Definiciones.GUI_COLOR_TEXTO);
			g.Escribir(m_leyenda, m_x - Video.Ancho / 2 + m_ancho / 2, m_y - Video.Alto / 2 + m_alto / 2, Superficie.H_CENTRO | Superficie.V_CENTRO);
		}
		#endregion



        /// <summary>
        /// Setea el ancho y el alto de boton
        /// </summary>
        /// <param name="alto">El alto deseado.</param>
        public void SetearAlto(int alto)
        {
            if (m_imagen == null)
            {
                m_alto = alto;
            }
        }

        /// <summary>
        /// Setea el ancho del boton
        /// </summary>
        /// <param name="ancho"></param>
        public void SetearAncho(int ancho)
        {
            if (m_imagen == null)
            {
                m_ancho = ancho;
            }
        }
    }//end Boton
}//end namespace GUI
