///////////////////////////////////////////////////////////
//  Hud.cs
//  Implementation of the Class Hud
//  Generated by Enterprise Architect
//  Created on:      04-ago-2008 20:09:00
//  Original author: Administrador
///////////////////////////////////////////////////////////

using System.Collections.Generic;
using Invasiones.Dibujo;
using Invasiones.Map;
using Invasiones.Nivel.Unidades;
using Invasiones.Recursos;
using Invasiones.Debug;
using System;
namespace Invasiones.GUI
{
	/// <summary>
	/// Despliega toda la información visible de unidades, ordenes, etsado de mapas,
	/// dentro del juego.
	/// </summary>
	public class Hud
	{
		#region Declaraciones

		/// <summary>
		/// Las posiciones en donde se va a situar el avatar.
		/// </summary>
		public const int AVATAR_X = 61;
		public const int AVATAR_Y = 11;

		public const int AVATAR_NOMBRE_X = 126;
		public const int AVATAR_NOMBRE_ANCHO = 82;
		public const int AVATAR_NOMBRE_Y = 6;

		public const int ATRIBUTOS_INICIO_X_1 = 141;
		public const int ATRIBUTOS_INICIO_X_2 = 215;
		public const int ATRIBUTOS_INICIO_X_3 = 338;

		public const int ATRIBUTOS_INICIO_Y = 25;
		public const int ATRIBUTOS_CANT_Y = 35;
		public const int ATRIBUTOS_CANT_INGL_X = 705;
		public const int ATRIBUTOS_CANT_ARG_X = 570;

		/// <summary>
		/// La imagen del hud.
		/// </summary>
		private Superficie m_imagen;

		/// <summary>
		/// La unidad que esta siendo seleccionada. Necesaria para imprimir sus atributos.
		/// </summary>
		private Unidad m_unidadAMostrar;

		/// <summary>
		/// La cantidad de enemigos actuales.
		/// </summary>
		private int m_cantidadEnemigos;

		/// <summary>
		/// La cantidad de argentinos que hay en el mapa.
		/// </summary>
		private int m_cantidadArgentinos;

		/// <summary>
		/// Posicion y del hud
		/// </summary>
		private int m_y;



        //pantalla de tips:
        private Tips m_tipVentana;

		#endregion

		#region Properties
		/// <summary>
		/// Setea la unidad seleccionada.
		/// </summary>
		public Unidad UnidadSeleccionada
		{
			set
			{
				m_unidadAMostrar = value;
			}
		}

		/// <summary>
		/// get y set de la cantidad de argentinos.
		/// </summary>
		public int CantidadArgentinos
		{
			get
			{
				return m_cantidadArgentinos;
			}
			set
			{
				m_cantidadArgentinos = value;
			}
		}

		/// <summary>
		/// get y set de la cantidad de enemigos.
		/// </summary>
		public int CantidadEnemigos
		{
			get
			{
				return m_cantidadEnemigos;
			}
			set
			{
				m_cantidadEnemigos = value;
			}
		}


		#endregion

		#region Constructores
		/// <summary>
		/// Construye el hud con la imagen del hud por defecto.
		/// </summary>
		public Hud()
		{
			m_imagen = AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_HUD);
			m_y = Video.Alto - m_imagen.Alto;

            m_tipVentana = new Tips();
            m_tipVentana.SetearPosicion(((Video.Ancho - m_tipVentana.Ancho) / 2) + 175, m_y - m_tipVentana.Alto - 75, 0);
           
            m_random = new Random();

        }
		#endregion

		#region Metodos

		/// <summary>
		/// Devuelve el alto del HUD
		/// </summary>
		public int Alto
		{
			get
			{
				return m_imagen.Alto;
			}
		}

		/// <summary>
		/// Actualiza el estado del hud. Itera por todos los elementos dentro de si mismo
		/// (botones, menues, etc.. )  y llama a su metodo actualizar.
		/// </summary>
		public void Actualizar()
		{
			//saco la unidad si se murio.
			if (m_unidadAMostrar != null && m_unidadAMostrar.EstaMuerto())
			{
				m_unidadAMostrar = null;
			}


            m_tipVentana.Actualizar();
		}
		int espaciadoLineas = 12;


        Random m_random;
		/// <summary>
		/// Dibuja el hud. Itera por cada uno de los componentes y llama al método Dibujar
		/// del componente.
		/// </summary>
		/// <param name="g">La pantalla a pintar el hud</param>
		public void Dibujar(Video g)
		{
			
            
            if (m_imagen != null)
			{
				g.Dibujar(m_imagen, 0, 0, Superficie.V_FONDO);
			}
            m_tipVentana.Dibujar(g);

			g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FNT.SANS12], Definiciones.COLOR_NEGRO);

			g.Escribir("" + m_cantidadEnemigos, ATRIBUTOS_CANT_INGL_X, m_y  + ATRIBUTOS_CANT_Y, 0);
			g.Escribir("" + m_cantidadArgentinos, ATRIBUTOS_CANT_ARG_X, m_y+ATRIBUTOS_CANT_Y, 0);
		
			g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FNT.SANS12], Definiciones.COLOR_BLANCO);


			if (m_unidadAMostrar != null)
			{
				if (m_unidadAMostrar.Avatar != null)
				{
					g.Dibujar(m_unidadAMostrar.Avatar, AVATAR_X, m_y + AVATAR_Y, 0);
				}
				if (m_unidadAMostrar.Nombre != null)
				{
					g.Escribir(m_unidadAMostrar.Nombre, AVATAR_NOMBRE_X, m_y + AVATAR_NOMBRE_Y, 0);
				}

				g.SetearColor(Definiciones.COLOR_NEGRO);

				g.Escribir(Texto.Strings[Res.STR_ALCANCE] + ": " + m_unidadAMostrar.Alcance,
					ATRIBUTOS_INICIO_X_1, m_y + (ATRIBUTOS_INICIO_Y), 0);

				g.Escribir(Texto.Strings[Res.STR_PUNTERIA] + ": " + m_unidadAMostrar.Punteria,
					ATRIBUTOS_INICIO_X_1, m_y + (ATRIBUTOS_INICIO_Y + espaciadoLineas), 0);

				g.Escribir(Texto.Strings[Res.STR_PUNTOS_DE_ATAQUE] + ": " + m_unidadAMostrar.PuntosDeAtaque,
					ATRIBUTOS_INICIO_X_2, m_y + (ATRIBUTOS_INICIO_Y), 0);

				g.Escribir(Texto.Strings[Res.STR_PUNTOS_DE_RESISTENCIA] + ": " + m_unidadAMostrar.Salud + "/" +
					m_unidadAMostrar.PuntosDeResistencia, ATRIBUTOS_INICIO_X_2, m_y + (ATRIBUTOS_INICIO_Y + espaciadoLineas), 0);

				g.Escribir(Texto.Strings[Res.STR_VELOCIDAD] + ": " + m_unidadAMostrar.VelocidadPorDefecto,
					ATRIBUTOS_INICIO_X_3, (m_y + ATRIBUTOS_INICIO_Y), 0);

				g.Escribir(Texto.Strings[Res.STR_VISIBILIDAD] + ": " + m_unidadAMostrar.Visibilidad,
					ATRIBUTOS_INICIO_X_3, m_y + (ATRIBUTOS_INICIO_Y + espaciadoLineas), 0);

			

			}
		}

       

		#endregion
	}//end Hud
}//end namespace GUI