///////////////////////////////////////////////////////////
//  Menu.cs
//  Implementation of the Class Menu
//  Generated by Enterprise Architect
//  Created on:      04-ago-2008 20:09:00
//  Original author: Administrador
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using Invasiones.Dibujo;
using Invasiones.Recursos;
using Invasiones.Eventos;

namespace Invasiones.GUI
{
	/// <summary>
	/// Clase que representa un menú.
	/// </summary>
	public class Menu : CajaGUI
	{
		#region Declaraciones
		/// <summary>
		/// La cantidad máxima de items que puede tener el menú.
		/// </summary>
		private const int MAX_CANTIDAD_ITEMS = 15;

		/// <summary>
		/// Flag para los ítems que esytan visibles
		/// </summary>
		public const int ITEM_VISIBLE = 1 << 1;

		/// <summary>
		/// Flag para los ítems que estan escondidos.
		/// </summary>
		public const int ITEM_ESCONDIDO = 1 << 2;

		/// <summary>
		/// Me dice si esta debajo del mouse o no.
		/// </summary>
		public const int ITEM_DEBAJO_DEL_MOUSE = 1 << 3;

		/// <summary>
		/// Dice si el item del menu fue seleccionado o no.
		/// </summary>
		public const int ITEM_SELECCIONADO = 1 << 4;

		/// <summary>
		/// Una lista con todos los ítems que se pueden elegir.
		/// </summary>
		private int[] m_items;

		/// <summary>
		/// Una lista con todos los ítems que se pueden elegir.
		/// </summary>
		private int m_cantidadDeItems;

		/// <summary>
		/// El ancho del ítem.
		/// </summary>
		private int m_botonAncho = 160;

		/// <summary>
		/// El alto de ítem
		/// </summary>
		private int m_botonAlto = 26;

		/// <summary>
		/// El espacio entre líneas del ítem.
		/// </summary>
		private int m_espacioEntreLineas = 1;

		/// <summary>
		/// La posición Y del menú.
		/// </summary>
		private int m_posicionOriginalY;

		/// <summary>
		/// La posición X del menú.
		/// </summary>
		private int m_posicionOriginalX;

		/// <summary>
		/// El ancla de donde tomar el X, Y
		/// </summary>
		private int m_ancla;

		#endregion

		#region Constructores
		/// <summary>
		/// Constructor de la clase.
		/// </summary>
		public Menu(Superficie imagen, int cantItem, int x, int y, int ancla)
		{

			m_imagen = imagen;

			//Por default no mas de MAX_CANTIDAD_ITEMS
			m_items = new int[MAX_CANTIDAD_ITEMS];
			m_cantidadDeItems = 0;
			if (cantItem == 3)
			{
				m_imagen = AdministradorDeRecursos.Instancia.ObtenerImagenAlpha(Res.IMG_MENU_3);
			}
			if (cantItem == 2)
			{
				m_imagen = AdministradorDeRecursos.Instancia.ObtenerImagenAlpha(Res.IMG_MENU_2);
			}
	
			m_posicionOriginalX = x;
			m_posicionOriginalY = y;

			m_ancla = ancla;

		}
		#endregion


		#region Metodos
		/// <summary>
		/// Dibuja el menu en la pantalla dada.
		/// </summary>
		/// <param name="gfx">La referencia a la pantalla donde se pintará.</param>
		public override void Dibujar(Video g)
		{

			if (m_imagen != null)
			{
				g.Dibujar(m_imagen, m_x, m_y - 6, 0);
			}

			int y = m_y;

			for (int i = 0; i < m_cantidadDeItems; i++)
			{
				//Si el ítem no esta escondido, lo escribo.
				if (((m_items[i] & 0xFF00) >> 8) != ITEM_ESCONDIDO)
				{
					if ((((m_items[i] & 0xFF00) >> 8) & ITEM_DEBAJO_DEL_MOUSE) != 0)
					{
						g.SetearColor(Definiciones.COLOR_NEGRO);
						g.LlenarRectangulo(m_x +2, y, m_botonAncho, m_botonAlto);
					}


					g.SetearFuente(m_fuente, Definiciones.GUI_COLOR_TEXTO);

					g.Escribir(m_items[i] & 0xFF, m_x - (Video.Ancho >> 1) + (m_botonAncho >> 1), y - (Video.Alto >> 1) + (m_botonAlto >> 1), Superficie.H_CENTRO | Superficie.V_CENTRO);
					y += m_espacioEntreLineas + m_botonAlto;
				}
			}
		}

		/// <summary>
		/// Actualiza el menú.
		/// </summary>
		/// <returns>Devuelve el ítem que fue seleccionado o -1 si ninguno fue seleccionado.</returns>
		public override int Actualizar()
		{
			int itemSeleccionado = -1;

			int y = m_y;

			for (int i = 0; i < m_cantidadDeItems; i++)
			{
				//Si el ítem no esta escondido no hago nada.
				if (((m_items[i] & 0xFF00) >> 8) != ITEM_ESCONDIDO)
				{
					if (Mouse.Instancia.X > m_x && Mouse.Instancia.X < (m_x + m_botonAncho) && Mouse.Instancia.Y > y && Mouse.Instancia.Y < (y + m_botonAlto))
					{
						m_items[i] |= (ITEM_DEBAJO_DEL_MOUSE << 8);
						if (Mouse.Instancia.BotonesApretados.Contains(Mouse.BOTON_IZQ))
						{
							m_items[i] |= (ITEM_SELECCIONADO << 8);
							itemSeleccionado = i;
						}
					}
					else
					{
						m_items[i] &= ~(ITEM_DEBAJO_DEL_MOUSE << 8);
					}
					y += m_espacioEntreLineas + m_botonAlto;
				}
			}

			return itemSeleccionado;
		}

		/// <summary>
		/// Setea la posicion en donde se va a pintar el menu.
		/// </summary>
		/// <param name="x">La posicion en x.</param>
		/// <param name="y">La posicion en y.</param>
		/// <param name="ancla">El ancla desde donde tomar el x, y</param>
		public override void SetearPosicion(int x, int y, int ancla)
		{
			m_posicionOriginalX = x;
			m_x = x;
			m_posicionOriginalY = y;
			m_y = y;
			m_ancla = ancla;

			if ((m_ancla & Superficie.H_CENTRO) != 0)
			{
				m_x = (Video.Ancho >> 1) - (m_botonAncho >> 1) + m_posicionOriginalX;
			}

			if ((m_ancla & Superficie.V_CENTRO) != 0)
			{
				m_y = (Video.Alto >> 1) + m_posicionOriginalY - (((m_botonAlto + m_espacioEntreLineas) * m_cantidadDeItems - m_espacioEntreLineas) >> 1);
			}
		}

		/// <summary>
		/// Agrega un ítem al menu.
		/// </summary>
		/// <param name="index">the index in the current map.</param>
		/// <param name="stringId">The string  id of the text to be displayed.</param>
		public bool AgregarItem(int index, int stringId, int flag)
		{
			if (index > MAX_CANTIDAD_ITEMS - 1)
			{
				return false;
			}

			if (m_cantidadDeItems == index)
			{
				m_cantidadDeItems++;
			}

			m_items[index] = (flag << 8) | (stringId & 0xFF);

			if ((m_ancla & Superficie.H_CENTRO) != 0)
			{
				m_x = (Video.Ancho >> 1) - (m_botonAncho >> 1) + m_posicionOriginalX;
			}

			if ((m_ancla & Superficie.V_CENTRO) != 0)
			{
				m_y = (Video.Alto >> 1) + m_posicionOriginalY - (((m_botonAlto + m_espacioEntreLineas) * m_cantidadDeItems - m_espacioEntreLineas) >> 1);
			}

			m_alto = m_imagen.Alto;
			m_ancho = m_imagen.Ancho;
			//m_ancho = m_botonAncho;
			//m_alto = (m_botonAlto + m_espacioEntreLineas) * m_cantidadDeItems - m_espacioEntreLineas;


			return true;
		}

		/// <summary>
		/// Setea la imagen de fondo.
		/// </summary>
		public void SetearImagen(Superficie sup)
		{
			m_imagen = sup;
		}

		/// <summary>
		/// Setea la fuente a utilizar para todos los ítems del menú.
		/// </summary>
		public void SetearFuente(Fuente fuente)
		{
			m_fuente = fuente;
		}
		#endregion
	}//end Menu
}//end namespace GUI