///////////////////////////////////////////////////////////
//  Batalla.cs
//  Implementation of the Class Batalla
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 3:01:56
//  Original author: Lucía
///////////////////////////////////////////////////////////

using Invasiones.SM;
using Invasiones.Map;
using Invasiones.Dibujo;
using Invasiones.Eventos;
using Invasiones.Recursos;
using Invasiones.Nivel.Unidades;
using Invasiones.Debug;
using System.Collections.Generic;
using Invasiones.GUI;
using System.Drawing;
using Invasiones.Nivel.Jugadores;
using System;

namespace Invasiones.Nivel
{
	public partial class Episodio
	{
		#region Declaraciones

		/// <summary>
		/// Los bandos a los que puede pertenecer una unidad.
		/// </summary>
		public enum BANDO
		{
			ENEMIGO,
			ARGENTINO
		}

        private const int CUENTA_HASTA_PREGUNTAR_REINICIAR = 50;

		/// <summary>
		/// Los estados en los que se puede encontrar a batalla.
		/// </summary>
		public enum ESTADO
		{
			FIN = -1,
			CARGANDO,
			JUGANDO,
			MOSTRAR_INTRODUCCION,
            MOSTRAR_OBJETIVOS,
			GANO,
            PERDIO
		}

		/// <summary>
		/// El boton siguiente dentro de la pantalla de mostrar objetivos.
		/// </summary>
		private Boton m_boton;

        private Boton m_botonAceptar;

		/// <summary>
		/// La lista con los ibstaculos que hay en pantalla (arbole, edificios, rocas, etc).
		/// </summary>
		private List<Obstaculo> m_obstaculos;

		/// <summary>
		/// El nivel actual, levantado desde el archivo xml.
		/// </summary>
		private Nivel m_nivelActual;

		/// <summary>
		/// El numero de nivel en el que esta el jugador.
		/// </summary>
		private int m_nroNivel;

		/// <summary>
		/// La matriz con todos los objetos a pintar.
		/// </summary>
		private Objeto[,] m_objetosAPintar;

		/// <summary>
		/// La posicion j de la camara (la posicion de la parte visible al usuario)
		/// </summary>
		private Camara m_camara;

		/// <summary>
		/// El objetivo actual a cumplir.
		/// </summary>
		private Objetivo m_objetivo;

		/// <summary>
		/// El enemigo.
		/// </summary>
		private BandoEnemigo m_enemigo;

		/// <summary>
		/// Los tiles semitransparentes que indican si se ve la porcion del mapa o no.
		/// </summary>
		private short[,] m_mapaTilesVisibles;

		/// <summary>
		/// El jugador.
		/// </summary>
		private BandoArgentino m_jugador;

		/// <summary>
		/// El m_mapa actual
		/// </summary>
		private Mapa m_mapa;

		/// <summary>
		/// El estado de la batalla.
		/// </summary>
		private Episodio.ESTADO m_estado;

		/// <summary>
		/// El hud de la pantalla.
		/// </summary>
		private Hud m_hud;

		/// <summary>
		/// lleva la cuenta del estado.
		/// </summary>
		private int m_cuenta;

		/// <summary>
		/// Me dice si tengo que mostrar el objetivo o no.
		/// </summary>
		private bool m_mostrarPopupObjetivo;

        private bool m_mostrarRecordatorioObjetivo;


		/// <summary>
		/// La cuenta para mostrar el objetivo actual
		/// </summary>
		private int m_cuentaMostrarObjetivo;

		/// <summary>
		/// La pagina actual del objetivo que se esta mostrando.
		/// </summary>
		private int m_paginaActual = 0;
		#endregion

		#region Propiedades
		/// <summary>
		/// Devuelve el estado de la batalla.
		/// </summary>
		public Episodio.ESTADO Estado
		{
			get
			{
				return m_estado;
			}
		}
		#endregion

		#region Metodos

		/// <summary>
		/// Constructor de la clase.
		/// </summary>
		public Episodio()
		{
            m_menuDeGameOver = new MenuDeConfirmacion(Res.STR_CONTINUARJUEGO, Res.STR_NO, Res.STR_SI);
            m_menuDeGameOver.SetearPosicion(0, 0, Superficie.V_CENTRO | Superficie.H_CENTRO);
 

        
        }

		/// <summary>
		/// Destructor de la clase.
		/// </summary>
		~Episodio()
		{
			this.Dispose();
		}

		/// <summary>
		/// Libera los recursos tomados.
		/// </summary>
		public virtual void Dispose()
		{
			if (m_mapa != null)
			{
				m_mapa.Dispose();
				m_mapa = null;
			}
			GC.SuppressFinalize(this);
		}

		/// <summary>
		/// Inicia la batalla cargada, o creada.
		/// </summary>
		public void Iniciar()
		{
			SetearEstado((int)ESTADO.CARGANDO);
		}

		/// <summary>
		/// Guarda la batalla actual.
		/// </summary>
		public bool Guardar()
		{
			return false;
		}

		/// <summary>
		/// Sale de la batalla.
		/// </summary>
		public void Salir()
		{

		}

		/// <summary>
		/// Dibuja la batalla.
		/// </summary>
		/// <param name="g">La referencia al Video.</param>
		public void Dibujar(Video g)
		{
			switch (m_estado)
			{
				case ESTADO.CARGANDO:
					DibujarEstadoCargando(g);
					break;

                case ESTADO.MOSTRAR_OBJETIVOS:
                    DibujarEstadoMostrarObjetivo(g);
                    break;

				case ESTADO.JUGANDO:
					DibujarEstadoJugando(g);
					break;

				case ESTADO.MOSTRAR_INTRODUCCION:
					DibujarEstadoMostrarIntroduccion(g);
					break;

				case ESTADO.GANO:
					DibujarEstadoGano(g);
					break;

                case ESTADO.PERDIO:
                    DibujarEstadoPerdio(g);
                    break;
			}

			g.SetearColor(Definiciones.COLOR_BLANCO);
#if DEBUG
            //g.Escribir("FPS: " + GameFrame.FPS, 0, 0, 0);
            //g.Escribir("UPS: " + GameFrame.UPS, 0, 20, 0);
#endif
		}

        private void DibujarEstadoMostrarObjetivo(Video g)
        {
            DibujarEstadoJugando(g);


            g.SetearColor(Definiciones.COLOR_OBJETIVOS);
            g.LlenarRectangulo(0, -m_hud.Alto /2, CAJA_OBJETIVOS_ANCHO, CAJA_OBJETIVOS_ALTO, Definiciones.ALPHA_OBJETIVOS, Superficie.V_CENTRO | Superficie.H_CENTRO);

            g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_TITULO], Definiciones.GUI_COLOR_TEXTO);
            g.Escribir(Res.STR_OBJETIVOS,0,  -m_hud.Alto / 2 -CAJA_OBJETIVOS_ALTO/2 + 50, Superficie.V_CENTRO | Superficie.H_CENTRO);
            g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_OBJETIVOS], Definiciones.GUI_COLOR_TEXTO);
            g.Escribir(Res.STR_PRIMER_BATALLA + m_paginaActual + (m_nivelActual.NroBatallaActual * Definiciones.PAGINAS_POR_INTRO), 0, -(m_hud.Alto >> 1) + 30, Superficie.V_CENTRO | Superficie.H_CENTRO);
            m_botonAceptar.Dibujar(g);
        }

		/// <summary>
		/// Dibuja el mensaje de que gano la batalla!!
		/// </summary>
		/// <param name="g"></param>
		private void DibujarEstadoGano(Video g)
		{
			DibujarEstadoJugando(g);
			m_boton.Dibujar(g);

			g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_GANO],Definiciones.COLOR_TEXTO_GANO) ;
			g.Escribir(Res.STR_GANASTE, 0, 0, Superficie.H_CENTRO | Superficie.V_CENTRO);
		}
        private MenuDeConfirmacion m_menuDeGameOver;

        private void DibujarEstadoPerdio(Video g)
        {
            DibujarEstadoJugando(g);

            g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_GANO], Definiciones.COLOR_TEXTO_GANO);
            g.Escribir(Res.STR_PERDISTE, 0, -100, Superficie.H_CENTRO | Superficie.V_CENTRO);
            
            if (m_cuenta > CUENTA_HASTA_PREGUNTAR_REINICIAR)
            {
                m_menuDeGameOver.Dibujar(g);
            }
        }

		#endregion

		/// <summary>
		/// Actualiza la batalla
		/// </summary>
		public bool Actualizar()
		{
			switch (m_estado)
			{
				case ESTADO.CARGANDO:
					ActualizarEstadoCargado();
					break;

				case ESTADO.MOSTRAR_INTRODUCCION:
					ActualizarEstadoMostrarIntroduccion();
					break;

                case ESTADO.MOSTRAR_OBJETIVOS:
                    ActualizarEstadoMostrarObjetivo();
                    break;

				case ESTADO.JUGANDO:
					ActualizarEstadoJugando();
					break;

				case ESTADO.GANO:
					ActualizarEstadoGano() ;
					break;

                case ESTADO.PERDIO:
                    ActualizarEstadoPerdio();
                    break;
			}
			return false;
		}


        private void ActualizarEstadoMostrarObjetivo()
        {
            if (m_cuenta == 0)
            {
                m_botonAceptar.SetearPosicion(0, CAJA_OBJETIVOS_OFFSET_BOTON_Y , Superficie.H_CENTRO| Superficie.V_CENTRO);
            }

            m_cuenta++;

            if (m_botonAceptar.Actualizar() != 0)
            {
                m_paginaActual++;
                if (m_paginaActual == Definiciones.PAGINAS_POR_INTRO)
                {
                    SetearEstado(ESTADO.JUGANDO);
                    m_mostrarPopupObjetivo = false;
                    m_mostrarRecordatorioObjetivo = true;
                }
            }
        }

        /// <summary>
        /// Actualiza el estado perdio.
        /// </summary>
        private void ActualizarEstadoPerdio()
        {


            if (m_cuenta++ < CUENTA_HASTA_PREGUNTAR_REINICIAR)
            {
                return;
            }

            int resultado = m_menuDeGameOver.Actualizar();

            if (resultado == (int)MenuDeConfirmacion.SELECCION.IZQUIERDO)
            {
                SetearEstado(ESTADO.FIN);
            }

            if (resultado == (int)MenuDeConfirmacion.SELECCION.DERECHO)
            { 
                SetearEstado(ESTADO.CARGANDO);
            }
        }


		/// <summary>
		/// Actualiza el estado gano.
		/// </summary>
		private void ActualizarEstadoGano()
		{
            if (m_boton.Actualizar() != 0) {
                SetearEstado(ESTADO.FIN);
            }
		}

		/// <summary>
		/// Setea un estado nuevo
		/// </summary>
		/// <returns></returns>
		private void SetearEstado(Episodio.ESTADO estado)
		{
			m_cuenta = 0;
			m_estado = estado;
            m_paginaActual = 0;

            if (estado == ESTADO.MOSTRAR_OBJETIVOS)
            {
                m_paginaActual = 2;
            }
		}

	}//end Batalla
}//end namespace Game