///////////////////////////////////////////////////////////
//  Font.cs
//  Implementation of the Class Font
//  Generated by Enterprise Architect
//  Created on:      19-May-2008 12:27:40 a.m.
//  Original author: Lucía
///////////////////////////////////////////////////////////

using System;
using Tao.Sdl;
using System.IO;
using Invasiones.Debug;
using System.Xml;
using Invasiones.Map;
using Invasiones.Recursos;

namespace Invasiones.Dibujo
{
    /// <summary>
    /// Wrapper de SDL para manejar fuentes ttf.
    /// </summary>
    public class Fuente
    {
        #region Declaraciones
        /// <summary>
        /// Puntero a ttf_font.
        /// </summary>
        private IntPtr m_fuente;

        /// <summary>
        /// El color actual de la fuente.
        /// </summary>
        private Sdl.SDL_Color m_color;
        #endregion

        #region Constructores
        /// <summary>
        /// Constructor de la clase.
        /// </summary>
        /// <param name="Id">El Id de la fuente.</param>
        /// <param name="size">El tamaño de la fuente. (ejemplo: 12, 16)</param>
        public Fuente(int id, int size)
        {
            m_fuente = SdlTtf.TTF_OpenFont(AdministradorDeRecursos.Instancia.PathsFuentes[id], size);

            if (m_fuente == IntPtr.Zero)
            {
                Log.Instancia.Error("No se pudo cargar la fuente " + AdministradorDeRecursos.Instancia.PathsFuentes[id]);
            }
            //Seteo el color por defecto en blanco - hardcodeado.
            m_color = new Sdl.SDL_Color(255, 255, 255);
        }
        #endregion

        #region Destructor - libera recursos
        /// <summary>
        /// Finalizador de la clase.
        /// </summary>
        ~Fuente()
        {
			Log.Instancia.Debug("bye fuente.");
			this.Dispose();
        }

        /// <summary>
        /// Libero al fuente utilizada.
        /// </summary>
        public virtual void Dispose()
        {
            if (m_fuente != IntPtr.Zero)
            {
				Log.Instancia.Debug("Elimino fuente: " + m_fuente);
                SdlTtf.TTF_CloseFont(m_fuente);
                m_fuente = IntPtr.Zero;
                GC.SuppressFinalize(this);
            }
        }
        #endregion

        #region Metodos
        /// <summary>
        /// Setea el color actual de la fuente.
        /// </summary>
        /// <param name="r">Color rojo.</param>
        /// <param name="g">Color verde.</param>
        /// <param name="b">Color azul.</param>
        /// <param name="a">Color aplha. 0 un color totalmente opaco.</param>
        public void SetearColor(byte r, byte g, byte b, byte a)
        {
            m_color = new Sdl.SDL_Color(r, g, b, a);
        }
        
        /// <summary>
        /// Devuelve un IntPtr a una SDL_Surface, apuntando al texto renderizado.
        /// </summary>
        /// <param name="text">El texto a renderizar.</param>
        public IntPtr ObtenerTextoRenderizado(string text)
        {
            if (m_fuente != null && text != null)
            {
                //TODO: investigar como hacer para que pueda escribir con TTF_RenderText_Shaded, porque es mas rápido.
                //Sdl.SDL_Color bgColor = new Sdl.SDL_Color(0,0,0,255);
                //IntPtr renderedText = SdlTtf.TTF_RenderText_Shaded(m_font, text, m_color, bgColor);
                return SdlTtf.TTF_RenderText_Blended(m_fuente, text, m_color);
            }
            return IntPtr.Zero;
        }
        #endregion
    }//end Font
}//end namespace Dibujo