///////////////////////////////////////////////////////////
//  PantallaMenuPpal.cs
//  Implementation of the Class PantallaMenuPpal
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 4:38:15
//  Original author: Lucia
///////////////////////////////////////////////////////////
using Invasiones.Dibujo;
using Invasiones.SM;
using Invasiones.Recursos;
using Invasiones.Eventos;
using Invasiones.GUI;
using Invasiones.Debug;
using System;
using Invasiones.Audio;

namespace Invasiones.Estados
{
	/// <summary>
	/// Es la clase que contiene el menu principal. Muestra el menu principal j
	/// direcciona al usuario a la opción que eligio.
	/// </summary>
	public class EstadoMenuPpal : Estado
	{
		/// <summary>
		/// La cantidad de ticks que tienen que pasar hasta que aparezca el menu.
		/// </summary>
		private const int CUENTA_HASTA_MOSTRAR_MENU = 20;

		/// <summary>
		/// La cantidad en que se incrementa la posicion del menu.
		/// </summary>
		private const int INCREMENTO_MENU_Y = 5;

		#region Declaraciones
		/// <summary>
		/// Contiene el Id del último item seleccionado.
		/// </summary>
		private int m_itemSeleccionado;

		/// <summary>
		/// EL menu conteniendo todos los ítems
		/// </summary>
		private Menu m_menu;

		/// <summary>
		/// La posicion deseada en y
		/// </summary>
		private int m_menuPosicionDeseadaY;

		/// <summary>
		/// La posicion en donde se esta pintando el menu.
		/// </summary>
		private int m_posicionY;

		/// <summary>
		/// Los items del menu.
		/// </summary>
		private enum ITEM
		{
			//CONTINUAR,
			NUEVO_JUEGO,
			//CARGAR_PARTIDA,
			//OPCIONES,
			//CREDITOS,
			AYUDA,
			SALIR
		}
		#endregion

        private bool m_primeraVezConstruido;
		#region Constructores
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="sm">Máquina de estados padre. Necesaria para poder cambiar de
		/// estados dentro de este estado.</param>
		public EstadoMenuPpal(MaquinaDeEstados stateMachine)
			: base(stateMachine)
		{
            m_primeraVezConstruido = true;
            
		}
		#endregion

		#region Destructor - libera recursos
		/// <summary>
		/// Class destructor.
		/// </summary>
		~EstadoMenuPpal()
		{

		}

		public void Dispose()
		{
			if (m_menu != null)
			{

				m_menu = null;
			}
			GC.SuppressFinalize(this);
		}
		#endregion

		#region Metodos Override
		/// <summary>
		/// Dibuja el estado.
		/// </summary>
		/// <param name="g">La pantalla en donde se dibujará el estado.</param>
		public override void Dibujar(Video g)
		{
			g.Dibujar(m_fondo, 0, 0, 0);

			//g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[(int) Definiciones.FNT.SANS20], Definiciones.COLOR_TITULO);
			//g.Escribir(Texto.Strings[Res.STR_MENU_PRINCIPAL], 0, Definiciones.TITULO_Y, Superficie.H_CENTRO);
			m_menu.Dibujar(g);

		}

		/// <summary>
		/// Actualiza el estado.
		/// </summary>
		public override void Actualizar()
		{


			if (m_cuenta++ > CUENTA_HASTA_MOSTRAR_MENU)
			{
				if (m_posicionY > m_menuPosicionDeseadaY)
				{
					m_posicionY -= INCREMENTO_MENU_Y;
				}
				m_menu.SetearPosicion(0, m_posicionY, Superficie.H_CENTRO);
			}

			m_itemSeleccionado = m_menu.Actualizar();

			switch (m_itemSeleccionado)
			{
				case (int)ITEM.NUEVO_JUEGO:
					m_maquinaDeEstados.SetearElProximoEstado(GameFrame.ESTADO.JUEGO);
					break;

				case (int)ITEM.AYUDA:
					m_maquinaDeEstados.SetearElProximoEstado(GameFrame.ESTADO.AYUDA);
					break;

				case (int)ITEM.SALIR:
					m_maquinaDeEstados.SetearElProximoEstado(GameFrame.ESTADO.SALIR);
					break;

			}

		}

		/// <summary>
		/// Inicializa el estado.
		/// </summary>
		public override void Iniciar()
		{
			m_fondo = AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_SPLASH);
			//Cambio el icono del cursor.
			Mouse.Instancia.SetearCursor(AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_CURSOR));

			//muestro el cursor en pantalla.
			Mouse.Instancia.MostrarCursor();

			Sonido.Instancia.Reproducir(Res.SFX_SPLASH, -1);

			m_menu = new Menu(null, 3, 0, Video.Alto - Definiciones.MENU_PRINCIPAL_Y_OFFSET, Superficie.H_CENTRO);

			if (!m_menu.AgregarItem((int)ITEM.NUEVO_JUEGO, Res.STR_MENU_NUEVO_JUEGO, Menu.ITEM_VISIBLE))
			{
				Log.Instancia.Debug("No se puede agregar el ítem " + (int)ITEM.NUEVO_JUEGO);
			}

			if (!m_menu.AgregarItem((int)ITEM.AYUDA, Res.STR_MENU_AYUDA, Menu.ITEM_VISIBLE))
			{
				Log.Instancia.Debug("No se puede agregar el ítem " + (int)ITEM.AYUDA);
			}

			if (!m_menu.AgregarItem((int)ITEM.SALIR, Res.STR_MENU_SALIR, Menu.ITEM_VISIBLE))
			{
				Log.Instancia.Debug("No se puede agregar el ítem " + ITEM.SALIR);
			}
            if (m_primeraVezConstruido)
            {
                m_primeraVezConstruido = false;
                m_menuPosicionDeseadaY = Video.Alto - m_menu.Alto - Definiciones.MENU_PRINCIPAL_Y_OFFSET;
                m_posicionY = Video.Alto + m_menu.Alto + Definiciones.MENU_PRINCIPAL_Y_OFFSET;
                m_menu.SetearPosicion(0, Video.Alto + 15, Superficie.H_CENTRO);
            }
            m_menu.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FUENTE_MENU]);

		}

		/// <summary>
		/// Sale del estado.
		/// </summary>
		public override void Salir()
		{
		}
		#endregion
	}//end PantallaMenuPpal
}