///////////////////////////////////////////////////////////
//  PantallaOpciones.cs
//  Implementation of the Class PantallaOpciones
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 5:12:34
//  Original author: Lucía
///////////////////////////////////////////////////////////

using Invasiones.SM;
using System;
using Invasiones.Dibujo;
using Invasiones.Recursos;
using Invasiones.GUI;

namespace Invasiones.Estados
{
	/// <summary>
	/// Esta pantalla es accedida por el menu principal luego de que se apreta la
	/// "Opciones" de la lista
	/// </summary>
    public class EstadoOpciones : Estado
    {
        /// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="stateMachine">Máquina de estados padre. Necesaria para poder
		/// cambiar de estados dentro de este estado.</param>
        public EstadoOpciones(MaquinaDeEstados stateMachine)
            : base(stateMachine)
        {
        }

        /// <summary>
        /// Dibuja el estado.
        /// </summary>
        /// <param name="gfx">La pantalla en donde se dibujará el estado.</param>
        public override void Dibujar(Video g)
        {
			g.Dibujar(m_fondo, 0, 0, 0);

			g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_TITULO], Definiciones.GUI_COLOR_TEXTO);
			g.Escribir(Res.STR_MENU_OPCIONES, 0, Definiciones.TITULO_Y, Superficie.H_CENTRO);
			m_boton.Dibujar(g);
        }

        /// <summary>
        /// Actualiza el estado.
        /// </summary>
        public override void Actualizar()
        {
			if (m_boton.Actualizar() != 0)
			{
				m_maquinaDeEstados.SetearElProximoEstado(GameFrame.ESTADO.MENU_PRINCIPAL);
			}
        }

        /// <summary>
        /// Inicializa el estado.
        /// </summary>
        public override void Iniciar()
        {
			m_fondo = AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_FONDO);
			m_boton = new Boton(Res.STR_BOTON_MENU, null);
			m_boton.SetearPosicion(Video.Ancho - m_boton.Ancho - Boton.OFFSET_LIMITE_PANTALLA,
				Video.Alto - m_boton.Alto - Boton.OFFSET_LIMITE_PANTALLA, 0);
        }


        /// <summary>
        /// Sale del estado.
        /// </summary>
        public override void Salir()
        {
        }



    }//end PantallaOpciones

}
