///////////////////////////////////////////////////////////
//  PantallaAyuda.cs
//  Implementation of the Class PantallaAyuda
//  Generated by Enterprise Architect
//  Created on:      22-jul-2008 5:12:33
//  Original author: Lucía
///////////////////////////////////////////////////////////

using Invasiones.SM;
using System;
using Invasiones.Dibujo;
using Invasiones.Recursos;
using Invasiones.GUI;
using Invasiones.Sprites;

namespace Invasiones.Estados
{
    public class EstadoAyuda : Estado
    {

        private enum ESTADO
        {
            SELECCIONAR,
            MOVER,
            ATACAR,
            OBJETIVO,
            SCROLL,
            HUD,
            SANAR,
            TIPS,
            GANAR,
            TOTAL_SUBESTADOS
        }

        ESTADO m_estado;


        protected Boton m_botonAtras;
        protected Boton m_botonSig;


        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="stateMachine">Máquina de estados padre. Necesaria para poder cambiar de
        /// estados dentro de este estado.</param>
        public EstadoAyuda(MaquinaDeEstados stateMachine)
            : base(stateMachine)
        {

        }

        /// <summary>
        /// Destructor. Libera todos los recursos utilizados.
        /// </summary>
        ~EstadoAyuda()
        {
        }

        private Animaciones m_screenshotActual;

        /// <summary>
        /// Dibuja el estado.
        /// </summary>
        /// <param name="gfx">La pantalla en donde se dibujará el estado.</param>
        public override void Dibujar(Video g)
        {
            g.Dibujar(m_fondo, 0, 0, 0);
            g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_TITULO], Definiciones.COLOR_TITULO);
            g.Escribir(Res.STR_MENU_AYUDA, 0, Definiciones.TITULO_Y, Superficie.H_CENTRO);

            if (m_estado < ESTADO.TOTAL_SUBESTADOS)
            {
                g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_TITULO_AYUDA], Definiciones.GUI_COLOR_TEXTO);
                g.Escribir(Res.STR_MENU_AYUDA_TEXTO_SELECCIONAR_01 + (int)m_estado * 2, 0, Definiciones.TEXTO_AYUDA_ITEM_Y, Superficie.H_CENTRO);

                g.SetearFuente(AdministradorDeRecursos.Instancia.Fuentes[Definiciones.FUENTE_AYUDA], Definiciones.GUI_COLOR_TEXTO);
                g.Escribir(Res.STR_MENU_AYUDA_TEXTO_SELECCIONAR_02 + (int)m_estado * 2, 0, Definiciones.TEXTO_AYUDA_Y, Superficie.H_CENTRO);
            }


            if (m_screenshotActual != null)
            {
                m_screenshotActual.Dibujar(g, 0, 150, Superficie.H_CENTRO | Superficie.V_CENTRO);
            }
            if (m_estado > ESTADO.SELECCIONAR)
            {
                m_botonAtras.Dibujar(g);
            }
            if (m_estado < ESTADO.GANAR)
            {
                m_botonSig.Dibujar(g);
            }
            else
            {
                m_boton.Dibujar(g);
            }
        }

        /// <summary>
        /// Actualiza el estado.
        /// </summary>
        public override void Actualizar()
        {
            if (m_boton.Actualizar() != 0)
            {
                m_estado++;

                if (m_estado > ESTADO.GANAR)
                {
                    m_maquinaDeEstados.SetearElProximoEstado(GameFrame.ESTADO.MENU_PRINCIPAL);
                }
                else
                {

                    if (m_estado < ESTADO.GANAR + 1)
                    {
                        m_screenshotActual = AdministradorDeRecursos.Instancia.Animaciones[Res.ANIM_AYUDA_SELECCION + (int)m_estado];
                        m_screenshotActual.Cargar();
                        m_screenshotActual.Reproducir();
                        m_screenshotActual.Loop = true;
                    }
                    else
                    {
                        m_screenshotActual = null;

                    }

                }
            }

            if (m_botonAtras.Actualizar() != 0)
            {
                if (m_estado > ESTADO.SELECCIONAR)
                {
                    m_estado--;

                    if (m_estado < ESTADO.GANAR + 1)
                    {
                        m_screenshotActual = AdministradorDeRecursos.Instancia.Animaciones[Res.ANIM_AYUDA_SELECCION + (int)m_estado];
                        m_screenshotActual.Cargar();
                        m_screenshotActual.Reproducir();
                        m_screenshotActual.Loop = true;
                    }
                }
            }

            if (m_screenshotActual != null)
            {
                m_screenshotActual.Actualizar();
            }

        }

        /// <summary>
        /// Inicializa el estado.
        /// </summary>
        public override void Iniciar()
        {
            m_fondo = AdministradorDeRecursos.Instancia.ObtenerImagen(Res.IMG_FONDO);

            m_boton = new Boton(Res.STR_BOTON_MENU, AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FNT.SANS18]);
            m_boton.SetearPosicion(Video.Ancho - m_boton.Ancho - Boton.OFFSET_LIMITE_PANTALLA, Video.Alto - m_boton.Alto - Boton.OFFSET_LIMITE_PANTALLA, 0);

            m_botonSig = new Boton(Res.STR_SIGUIENTE, AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FNT.SANS18]);
            m_botonSig.SetearPosicion(Video.Ancho - m_boton.Ancho - Boton.OFFSET_LIMITE_PANTALLA, Video.Alto - m_boton.Alto - Boton.OFFSET_LIMITE_PANTALLA, 0);

            m_botonAtras = new Boton(Res.STR_ATRAS, AdministradorDeRecursos.Instancia.Fuentes[(int)Definiciones.FNT.SANS18]);
            m_botonAtras.SetearPosicion(Video.Ancho - (m_boton.Ancho * 2) - Boton.OFFSET_LIMITE_PANTALLA, Video.Alto - m_boton.Alto - Boton.OFFSET_LIMITE_PANTALLA, 0);


            m_estado = ESTADO.SELECCIONAR;

            m_screenshotActual = AdministradorDeRecursos.Instancia.Animaciones[Res.ANIM_AYUDA_SELECCION + (int)m_estado];
            m_screenshotActual.Cargar();
            m_screenshotActual.Reproducir();
            m_screenshotActual.Loop = true;
        }


        /// <summary>
        /// Sale del estado.
        /// </summary>
        public override void Salir()
        {

        }


    }//end PantallaAyuda

}
