///////////////////////////////////////////////////////////
//  SoundServer.cs
//  Implementation of the Class SoundServer
//  Generated by Enterprise Architect
//  Created on:      18-May-2008 09:33:15 m_puntoComienzo.m.
//  Original author: Lucía
///////////////////////////////////////////////////////////


using Tao.Sdl;
using Invasiones.Debug;
using System;
using Invasiones.Map;
using System.IO;
using System.Xml;
using Invasiones.Recursos;

namespace Invasiones.Audio
{
    /// <summary>
	/// Esta clase contiene todo lo necesario para reproducir sonidos. Se pueden
	/// reproducir más de un sonido a la vez. Hace diferencia del sonido de fondo j los
	/// sonidos de efectos especiales. Es un wrapper a SdlMixer.
	/// Corresponde al patrón Singleton
	/// Cualquier clase que necesite reproducir un sonido utiliza los métodos de la
	/// clase Sonido.
	/// Ver Diagrama de Despliegue del Famework.
	/// </summary>
    public class Sonido
    {
        /// <summary>
        /// El número de sonidos concurrentes
        /// </summary>
        private const int NRO_DE_CANALES_DE_MEZCLA = 32;

        /// <summary>
        /// El volumen máximo del sonido
        /// </summary>
        private const int VOLUMEN_POR_DEFECTO = 100;

        /// <summary>
        /// La cantidad máxima de sonidos simultáneos
        /// </summary>
        private const int CANALES_MAXIMOS_SIMULTANEOS = Res.SND_COUNT;

        /// <summary>
        /// La música de fondo actual siendo reproducida. -1 Si niguna se esta
        /// reproduciendo.
        /// </summary>
        private int m_musicaDeFondoActual;

        /// <summary>
        /// La instancia de esta clase.
        /// </summary>
        private static Sonido s_instancia;



        /// <summary>
        /// El puntero IntPtr al Mix_Music.
        /// </summary>
        private IntPtr[] m_todaLaMusica;

        /// <summary>
        /// El puntero IntPtr al Mix_Chunk.
        /// </summary>
        private IntPtr[] m_todosLosSFX;

        /// <summary>
        /// Contiene los estados de cada sonido
        /// </summary>
        private int[] m_estadoDeTodosLosSFX;


        /// <summary>
        /// Delegado SdlMixer.MusicFinished. Se llama cuando un sonido o deja de
        /// reproducirse.
        /// </summary>
        private static SdlMixer.MusicFinishedDelegate s_musicaFinalizada;


        /// <summary>
        /// Delegado SdlMixer.ChannelFinishedDelegate. Se llama cuando un sonido deja de
        /// reproducirse.
        /// </summary>
        private static SdlMixer.ChannelFinishedDelegate s_canalFinalizado;

        /// <summary>
        /// Constructor. Declarado private para que haya solamente una instancia.
        /// </summary>
        private Sonido()
        {
        }

		/// <summary>
		/// Inicializa el subsistema de sonidos.
		/// </summary>
		public void Inicializar()
		{
			//if (1 == 1) return;
			//This is where we open up our audio device.  Mix_OpenAudio takes
			//as its parameters the audio format we'd /like/ to have. 
			//audio frqeuency: 22050, half cds frequency.
			//Sdl.AUDIO_S16SYS: Signed 16-bit samples, in system byte order
			//chanel: Number of sound channels in output. Set to 2 for stereo, 1 for mono. This has nothing to do with mixing channels. 
			//4096: Bytes used per output sample. 
			if (SdlMixer.Mix_OpenAudio(22050, (short)Sdl.AUDIO_S16SYS, 2, 4096) != 0)
			{
				Log.Instancia.Error("Unable to open audio!\n");
			}


			//SdlMixer.Mix_AllocateChannels(NRO_DE_CANALES_DE_MEZCLA);

			s_musicaFinalizada = MusicaFinalizada;
			s_canalFinalizado = CanalFinalizado;
		}

        /// <summary>
        /// Destructor. Libera la api Mixer
        /// </summary>
        ~Sonido()
        {
          
        }

		public virtual void Dispose()
		{
			//Apago y libero la api Mixer
			SdlMixer.Mix_CloseAudio();
			GC.SuppressFinalize(this);
		}


        /// <summary>
        /// Libera todos los sonidos j toda la música de fondo.
        /// </summary>
        private void LiberarTodosLosSonidos()
        {
            //libero toda la música de fondo
            if (m_todaLaMusica != null)
            {
                for (int i = 0; i < m_todaLaMusica.Length; i++)
                {
                    SdlMixer.Mix_FreeMusic(m_todaLaMusica[i]);
                }
            }

            //libero todos los sonidos
            if (m_todosLosSFX != null)
            {
                for (int i = 0; i < m_todosLosSFX.Length; i++)
                {
                    SdlMixer.Mix_FreeChunk(m_todosLosSFX[i]);
                }
            }
        }

        /// <summary>
        /// Carga todos los sonidos. Se supone que los sonidos estan guardados de la siguient manera 
        /// (dentro de los paths del xml): Los primeros hasta SND_COUNT son MP3s j representan a la
        /// música de fondo. Los siguientes hasta SFX_COUNT son WAVs j representan a los sondidos especiales.
        /// </summary>
        public bool CargarTodosLosSonidos()
        {
			//if (1 == 1) return false;
			///SdlMixer.Mix_AllocateChannels(CANALES_MAXIMOS_SIMULTANEOS);
            //Cargo la música
            if (m_todaLaMusica == null)
            {
                m_todaLaMusica = new IntPtr[Res.SND_COUNT];

                if (AdministradorDeRecursos.Instancia.PathsSonidos == null)
                {
                    Log.Instancia.Debug("No esta cargado m_soundPaths");
                    return false;
                }

                for (int i = 0; i < Res.SND_COUNT; i++)
                {
                    m_todaLaMusica[i] = SdlMixer.Mix_LoadMUS(AdministradorDeRecursos.Instancia.PathsSonidos[i]);

                    if (m_todaLaMusica[i] == IntPtr.Zero)
                    {
                        Log.Instancia.Error("No se pudo cargar el sonido. error " + SdlMixer.Mix_GetError());
                        return false;
                    }
                }
            }

            //cargo los sonidos
            if (m_todosLosSFX == null)
            {
                m_todosLosSFX = new IntPtr[Res.SFX_COUNT];
                m_estadoDeTodosLosSFX = new int[Res.SFX_COUNT];

                if (AdministradorDeRecursos.Instancia.PathsSonidos == null)
                {
                    Log.Instancia.Debug("No esta cargado m_soundPaths");
                    return false;
                }


                for (int i = Res.SND_COUNT, j = 0; i < Res.SFX_COUNT + Res.SND_COUNT; i++, j++)
                {
                    m_todosLosSFX[j] = SdlMixer.Mix_LoadWAV(AdministradorDeRecursos.Instancia.PathsSonidos[i]);
                    if (m_todosLosSFX[j] == IntPtr.Zero)
                    {
                        Log.Instancia.Error("No se pudo cargar el sonido. error " + SdlMixer.Mix_GetError());
                        return false;
                    }
                    SdlMixer.Mix_VolumeChunk(m_todosLosSFX[j], VOLUMEN_POR_DEFECTO);

                    m_estadoDeTodosLosSFX[j] = -1;
                }
                //


            }

            m_musicaDeFondoActual = -1;
            return true;
        }

        /// <summary>
        /// Setea el volumen.
        /// </summary>
        /// <param name="Id">Id del sonido al que quiero cambiar el volumen. -1 para setear el volumen a todos.</param>
        /// <param name="volume">El nivel de volumen que deseo. De 0 a 128</param>
        public void SetearVolumen(int id, int volume)
        {
            if (id < -1 || id >= Res.SND_COUNT + Res.SFX_COUNT)
            {
                Log.Instancia.Advertir("No se puede setear el volumen a" + id + ". El sonido no existe.");
                return;
            }

            if (volume > 128)
            {
                volume = 128;
            }
            if (volume < 0)
            {
                volume = 0;
            }

            // Si deseo setear el volumen a todos
            if (id == -1)
            {
                //Seteo el volumen de todos los sonidos
                for (int i = 0, j = Res.SND_COUNT; i < m_todosLosSFX.Length; i++, j++)
                {
                    // devuelve el volumen previo... por ahora no es necesario, creo que tampoco lo va  ser.
                    SdlMixer.Mix_VolumeChunk(m_todosLosSFX[i], volume);
                }
                //steo el volumen de la musica
                // devuelve el volumen previo... por ahora no es necesario, creo que tampoco lo va  ser.
                SdlMixer.Mix_VolumeMusic(volume);
                return;
            }


            //se trata de un efecto especial
            if (id >= Res.SND_COUNT)
            {
                // devuelve el volumen previo... por ahora no es necesario, creo que tampoco lo va  ser.
                SdlMixer.Mix_VolumeChunk(m_todosLosSFX[id - Res.SND_COUNT], volume);
            }
            //se trata de una música de fondo
            else
            {
                // devuelve el volumen previo... por ahora no es necesario, creo que tampoco lo va  ser.
                SdlMixer.Mix_VolumeMusic(volume);
            }
        }




        /// <summary>
        /// Pausa el sonido dado por parámetro.
        /// (ver si tiene algun uso)
        /// </summary>
        /// <param name="Id">El Id del sonido a pausar. -1 para pausar a todos</param>
        public void Pausar(int id)
        {
            if (id < -1 || id >= Res.SND_COUNT + Res.SFX_COUNT)
            {
                Log.Instancia.Advertir("No se puede pausar el sonido " + id + ". El sonido no existe.");
                return;
            }
            // si deseo pausar a todos los sonidos
            if (id == -1)
            {
                SdlMixer.Mix_Pause(-1);
                SdlMixer.Mix_PauseMusic();
                return;
            }

            //Se trata de algun sonido especial
            if (id >= Res.SND_COUNT)
            {
                SdlMixer.Mix_Pause(id - Res.SND_COUNT);
            }
            // se trata de algun sonido de fondo
            else
            {
                SdlMixer.Mix_PauseMusic();
            }
        }

        /// <summary>
        /// Reanuda el efecto especial pasado por parámetro
        /// </summary>
        /// <param name="Id">El Id del sonido a reanudar.  -1 para reanudar a todos</param>
        public void Reanudar(int id)
        {
            if (id < -1 || id >= Res.SND_COUNT + Res.SFX_COUNT)
            {
                Log.Instancia.Advertir("No se puede reanudar el sonido " + id + ". El sonido no existe.");
                return;
            }
            if (id == -1)
            {
                SdlMixer.Mix_Resume(-1);
                SdlMixer.Mix_ResumeMusic();
                return;
            }
            //Se trata de algun sonido especial
            if (id >= Res.SND_COUNT)
            {
                SdlMixer.Mix_Resume(id - Res.SND_COUNT);
            }
            // se trata de algun sonido de fondo
            else
            {
                SdlMixer.Mix_ResumeMusic();
            }
        }

        /// <summary>
        /// Esta el la función que le dijimos al SDL_Mixer que llame cuando una
        /// música de fondo ha terminado.
        /// </summary>
        private void MusicaFinalizada()
        {
            m_musicaDeFondoActual = -1;
        }

        /// <summary>
        /// Esta el la función que le dijimos al SDL_Mixer que llame cuando un
        /// efecto especial ha terminado.
        /// </summary>
        private void CanalFinalizado(int channel)
        {
            m_estadoDeTodosLosSFX[channel] = -1;
        }

        /// <summary>
        /// Toca el sonido "Id". Devuelve true si pudo tocar el sonido satisfactoriamente.
        /// </summary>
        /// <param name="Id">El sonido a tocar</param>
        /// <param name="loop">Las veces que se va a reproducir el sonido. Usa -1 para tocar infinitas
        /// veces, y 0 para tocarla solamente una vez</param>
        public bool Reproducir(int id, int loop)
        {
			//if (1 == 1) return false;
			//Log.Instancia.Debug("Reproduzco sonido: " + id);
            if (id < 0 || id >= Res.SND_COUNT + Res.SFX_COUNT)
            {
                Log.Instancia.Advertir("No se puede reproducir el sonido " + id + ". El sonido no existe.");
                return false;
            }

            //si quiero tocar un sfx
            if (id >= Res.SND_COUNT)
            {
				if (m_estadoDeTodosLosSFX[id - Res.SND_COUNT] != -1)
				{
				    // no queremos volver a tocar un sonido que ya esta reproduciendose.
				    return false;
				}

				if (m_estadoDeTodosLosSFX[id - Res.SND_COUNT] == -1)
				{
                    m_estadoDeTodosLosSFX[id - Res.SND_COUNT] = id;

                    id -= Res.SND_COUNT;
                    if (loop < -1)
                    {
                        loop = 0;
                    }

                    //inicio el sonido
                    if (SdlMixer.Mix_PlayChannel(id, m_todosLosSFX[id], loop) == -1)
                    {
                        Log.Instancia.Error("No se pudo tocar el sonido " + (id + Res.SND_COUNT) + ". " + SdlMixer.Mix_GetError());
                    }

                    SdlMixer.Mix_ChannelFinished(s_canalFinalizado);
				}

            }

            //si quiero tocar una música de fondo
            else
            {

                if (m_todaLaMusica[id] != IntPtr.Zero)
                {
                    if (id == m_musicaDeFondoActual)
                    {
                        // no queremos volver a tocar un sonido que ya esta reproduciendose.
                        return false;
                    }

                    m_musicaDeFondoActual = id;

                    //Esto inicializa la repriducción de la música
                    if (SdlMixer.Mix_PlayMusic(m_todaLaMusica[id], loop) != 0)
                    {
                        Log.Instancia.Error("No se pudo tocar el sonido. error " + SdlMixer.Mix_GetError());
                        return false;
                    }

                    //queremos saber cuando exactamente ha parado la reproducción. 
                    SdlMixer.Mix_HookMusicFinished(s_musicaFinalizada);
                    return true;
                }
            }
            return true;
        }

        /// <summary>
        /// Devuelve la instancia de la clase.
        /// </summary>
        public static Sonido Instancia
        {
            get
            {
                if (s_instancia == null)
                {
                    s_instancia = new Sonido();
                }
                return s_instancia;
            }
        }


        /// <summary>
        /// Para el sonido dado.
        /// </summary>
        /// <param name="Id">El Id del sonido a parar. -1 para parar a todos.</param>
        public void Parar(int id)
        {
            if (id < -1 || id >= Res.SND_COUNT + Res.SFX_COUNT)
            {
                Log.Instancia.Advertir("No se puede parar el sonido " + id + ". El sonido no existe.");
                return;
            }
            if (id == -1)
            {
                SdlMixer.Mix_HaltMusic();
                SdlMixer.Mix_HaltChannel(-1);
                return;
            }

            if (id >= Res.SND_COUNT)
            {
                SdlMixer.Mix_HaltChannel(id - Res.SND_COUNT);
            }
            else
            {
                SdlMixer.Mix_HaltMusic();
            }
        }

        /// <summary>
        /// Para la música de fondo.
        /// </summary>
        public void PararMusicaDeFondo()
        {
            SdlMixer.Mix_HaltMusic();
        }

    }//end SoundServer

}//end namespace Sound